<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ApiKeyAuthCredentials
{
    /**
     * String value for authorization.
     */
    public function getAuthorization(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Use `Authorization: Token <API_KEY>` Example: `Authorization:
     *        Token 12345abcdef`
     */
    public function equals(string $authorization): bool;
}
