<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Authentication;

use Core\Authentication\CoreAuth;
use DeepgramLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class ApiKeyAuthManager extends CoreAuth implements ApiKeyAuthCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(HeaderParam::init('Authorization', $this->getAuthorization())->requiredNonEmpty());
    }

    /**
     * String value for authorization.
     */
    public function getAuthorization(): string
    {
        return $this->config['authorization'] ?? ConfigurationDefaults::AUTHORIZATION;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization Use `Authorization: Token <API_KEY>` Example: `Authorization:
     *        Token 12345abcdef`
     */
    public function equals(string $authorization): bool
    {
        return $authorization == $this->getAuthorization();
    }
}
