<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\AgentConfigurationV1;

/**
 * Builder for model AgentConfigurationV1
 *
 * @see AgentConfigurationV1
 */
class AgentConfigurationV1Builder
{
    /**
     * @var AgentConfigurationV1
     */
    private $instance;

    private function __construct(AgentConfigurationV1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Agent Configuration V1 Builder object.
     *
     * @param string $agentId
     * @param array $config
     */
    public static function init(string $agentId, array $config): self
    {
        return new self(new AgentConfigurationV1($agentId, $config));
    }

    /**
     * Sets metadata field.
     *
     * @param array<string,string>|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param \DateTime|null $value
     */
    public function updatedAt(?\DateTime $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Agent Configuration V1 object.
     */
    public function build(): AgentConfigurationV1
    {
        return CoreHelper::clone($this->instance);
    }
}
