<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\AgentThinkModelsV1Response;
use DeepgramLib\Models\AgentThinkModelsV1ResponseModelsItems0;
use DeepgramLib\Models\AgentThinkModelsV1ResponseModelsItems1;
use DeepgramLib\Models\AgentThinkModelsV1ResponseModelsItems2;
use DeepgramLib\Models\AgentThinkModelsV1ResponseModelsItems3;
use DeepgramLib\Models\AgentThinkModelsV1ResponseModelsItems4;

/**
 * Builder for model AgentThinkModelsV1Response
 *
 * @see AgentThinkModelsV1Response
 */
class AgentThinkModelsV1ResponseBuilder
{
    /**
     * @var AgentThinkModelsV1Response
     */
    private $instance;

    private function __construct(AgentThinkModelsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Agent Think Models V1 Response Builder object.
     *
     * @param array<AgentThinkModelsV1ResponseModelsItems0|AgentThinkModelsV1ResponseModelsItems1|AgentThinkModelsV1ResponseModelsItems2|AgentThinkModelsV1ResponseModelsItems3|AgentThinkModelsV1ResponseModelsItems4> $models
     */
    public static function init(array $models): self
    {
        return new self(new AgentThinkModelsV1Response($models));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Agent Think Models V1 Response object.
     */
    public function build(): AgentThinkModelsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
