<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\AgentThinkModelsV1ResponseModelsItems2;

/**
 * Builder for model AgentThinkModelsV1ResponseModelsItems2
 *
 * @see AgentThinkModelsV1ResponseModelsItems2
 */
class AgentThinkModelsV1ResponseModelsItems2Builder
{
    /**
     * @var AgentThinkModelsV1ResponseModelsItems2
     */
    private $instance;

    private function __construct(AgentThinkModelsV1ResponseModelsItems2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Agent Think Models V1 Response Models Items 2 Builder object.
     *
     * @param string $id
     * @param string $name
     * @param array $provider
     */
    public static function init(string $id, string $name, array $provider): self
    {
        return new self(new AgentThinkModelsV1ResponseModelsItems2($id, $name, $provider));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Agent Think Models V1 Response Models Items 2 object.
     */
    public function build(): AgentThinkModelsV1ResponseModelsItems2
    {
        return CoreHelper::clone($this->instance);
    }
}
