<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\AgentVariableV1;

/**
 * Builder for model AgentVariableV1
 *
 * @see AgentVariableV1
 */
class AgentVariableV1Builder
{
    /**
     * @var AgentVariableV1
     */
    private $instance;

    private function __construct(AgentVariableV1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Agent Variable V1 Builder object.
     *
     * @param string $variableId
     * @param string $key
     * @param array $value
     */
    public static function init(string $variableId, string $key, array $value): self
    {
        return new self(new AgentVariableV1($variableId, $key, $value));
    }

    /**
     * Sets created at field.
     *
     * @param \DateTime|null $value
     */
    public function createdAt(?\DateTime $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets updated at field.
     *
     * @param \DateTime|null $value
     */
    public function updatedAt(?\DateTime $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Agent Variable V1 object.
     */
    public function build(): AgentVariableV1
    {
        return CoreHelper::clone($this->instance);
    }
}
