<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\CreateKeyV1Response;

/**
 * Builder for model CreateKeyV1Response
 *
 * @see CreateKeyV1Response
 */
class CreateKeyV1ResponseBuilder
{
    /**
     * @var CreateKeyV1Response
     */
    private $instance;

    private function __construct(CreateKeyV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Key V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateKeyV1Response());
    }

    /**
     * Sets api key id field.
     *
     * @param string|null $value
     */
    public function apiKeyId(?string $value): self
    {
        $this->instance->setApiKeyId($value);
        return $this;
    }

    /**
     * Sets key field.
     *
     * @param string|null $value
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets comment field.
     *
     * @param string|null $value
     */
    public function comment(?string $value): self
    {
        $this->instance->setComment($value);
        return $this;
    }

    /**
     * Sets scopes field.
     *
     * @param string[]|null $value
     */
    public function scopes(?array $value): self
    {
        $this->instance->setScopes($value);
        return $this;
    }

    /**
     * Sets tags field.
     *
     * @param string[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets expiration date field.
     *
     * @param \DateTime|null $value
     */
    public function expirationDate(?\DateTime $value): self
    {
        $this->instance->setExpirationDate($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Create Key V1 Response object.
     */
    public function build(): CreateKeyV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
