<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\CreateProjectInviteV1Response;

/**
 * Builder for model CreateProjectInviteV1Response
 *
 * @see CreateProjectInviteV1Response
 */
class CreateProjectInviteV1ResponseBuilder
{
    /**
     * @var CreateProjectInviteV1Response
     */
    private $instance;

    private function __construct(CreateProjectInviteV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Project Invite V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateProjectInviteV1Response());
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Create Project Invite V1 Response object.
     */
    public function build(): CreateProjectInviteV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
