<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\CreateAgentConfigurationV1Request;

/**
 * Builder for model CreateAgentConfigurationV1Request
 *
 * @see CreateAgentConfigurationV1Request
 */
class CreateAgentConfigurationV1RequestBuilder
{
    /**
     * @var CreateAgentConfigurationV1Request
     */
    private $instance;

    private function __construct(CreateAgentConfigurationV1Request $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Agent Configuration V1 Request Builder object.
     *
     * @param string $config
     */
    public static function init(string $config): self
    {
        return new self(new CreateAgentConfigurationV1Request($config));
    }

    /**
     * Sets metadata field.
     *
     * @param array<string,string>|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets api version field.
     *
     * @param int|null $value
     */
    public function apiVersion(?int $value): self
    {
        $this->instance->setApiVersion($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Create Agent Configuration V1 Request object.
     */
    public function build(): CreateAgentConfigurationV1Request
    {
        return CoreHelper::clone($this->instance);
    }
}
