<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\CreateProjectDistributionCredentialsV1Response;
use RestApiLib\Models\CreateProjectDistributionCredentialsV1ResponseDistributionCredentials;
use RestApiLib\Models\CreateProjectDistributionCredentialsV1ResponseMember;

/**
 * Builder for model CreateProjectDistributionCredentialsV1Response
 *
 * @see CreateProjectDistributionCredentialsV1Response
 */
class CreateProjectDistributionCredentialsV1ResponseBuilder
{
    /**
     * @var CreateProjectDistributionCredentialsV1Response
     */
    private $instance;

    private function __construct(CreateProjectDistributionCredentialsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Project Distribution Credentials V1 Response Builder object.
     *
     * @param CreateProjectDistributionCredentialsV1ResponseMember $member
     * @param CreateProjectDistributionCredentialsV1ResponseDistributionCredentials $distributionCredentials
     */
    public static function init(
        CreateProjectDistributionCredentialsV1ResponseMember $member,
        CreateProjectDistributionCredentialsV1ResponseDistributionCredentials $distributionCredentials
    ): self {
        return new self(new CreateProjectDistributionCredentialsV1Response($member, $distributionCredentials));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Create Project Distribution Credentials V1 Response object.
     */
    public function build(): CreateProjectDistributionCredentialsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
