<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\CreateAgentVariableV1Request;

/**
 * Builder for model CreateAgentVariableV1Request
 *
 * @see CreateAgentVariableV1Request
 */
class CreateAgentVariableV1RequestBuilder
{
    /**
     * @var CreateAgentVariableV1Request
     */
    private $instance;

    private function __construct(CreateAgentVariableV1Request $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Agent Variable V1 Request Builder object.
     *
     * @param string $key
     * @param array $value
     */
    public static function init(string $key, array $value): self
    {
        return new self(new CreateAgentVariableV1Request($key, $value));
    }

    /**
     * Sets api version field.
     *
     * @param int|null $value
     */
    public function apiVersion(?int $value): self
    {
        $this->instance->setApiVersion($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Create Agent Variable V1 Request object.
     */
    public function build(): CreateAgentVariableV1Request
    {
        return CoreHelper::clone($this->instance);
    }
}
