<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ErrorResponseModernError;

/**
 * Builder for model ErrorResponseModernError
 *
 * @see ErrorResponseModernError
 */
class ErrorResponseModernErrorBuilder
{
    /**
     * @var ErrorResponseModernError
     */
    private $instance;

    private function __construct(ErrorResponseModernError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Response Modern Error Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorResponseModernError());
    }

    /**
     * Sets category field.
     *
     * @param string|null $value
     */
    public function category(?string $value): self
    {
        $this->instance->setCategory($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param string|null $value
     */
    public function details(?string $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets request id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Response Modern Error object.
     */
    public function build(): ErrorResponseModernError
    {
        return CoreHelper::clone($this->instance);
    }
}
