<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ErrorResponseLegacyError;

/**
 * Builder for model ErrorResponseLegacyError
 *
 * @see ErrorResponseLegacyError
 */
class ErrorResponseLegacyErrorBuilder
{
    /**
     * @var ErrorResponseLegacyError
     */
    private $instance;

    private function __construct(ErrorResponseLegacyError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Response Legacy Error Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorResponseLegacyError());
    }

    /**
     * Sets err code field.
     *
     * @param string|null $value
     */
    public function errCode(?string $value): self
    {
        $this->instance->setErrCode($value);
        return $this;
    }

    /**
     * Sets err msg field.
     *
     * @param string|null $value
     */
    public function errMsg(?string $value): self
    {
        $this->instance->setErrMsg($value);
        return $this;
    }

    /**
     * Sets request id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Response Legacy Error object.
     */
    public function build(): ErrorResponseLegacyError
    {
        return CoreHelper::clone($this->instance);
    }
}
