<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\GetModelV1ResponseOneOf1Metadata;

/**
 * Builder for model GetModelV1ResponseOneOf1Metadata
 *
 * @see GetModelV1ResponseOneOf1Metadata
 */
class GetModelV1ResponseOneOf1MetadataBuilder
{
    /**
     * @var GetModelV1ResponseOneOf1Metadata
     */
    private $instance;

    private function __construct(GetModelV1ResponseOneOf1Metadata $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Model V1 Response One Of 1 Metadata Builder object.
     */
    public static function init(): self
    {
        return new self(new GetModelV1ResponseOneOf1Metadata());
    }

    /**
     * Sets accent field.
     *
     * @param string|null $value
     */
    public function accent(?string $value): self
    {
        $this->instance->setAccent($value);
        return $this;
    }

    /**
     * Sets age field.
     *
     * @param string|null $value
     */
    public function age(?string $value): self
    {
        $this->instance->setAge($value);
        return $this;
    }

    /**
     * Sets color field.
     *
     * @param string|null $value
     */
    public function color(?string $value): self
    {
        $this->instance->setColor($value);
        return $this;
    }

    /**
     * Sets image field.
     *
     * @param string|null $value
     */
    public function image(?string $value): self
    {
        $this->instance->setImage($value);
        return $this;
    }

    /**
     * Sets sample field.
     *
     * @param string|null $value
     */
    public function sample(?string $value): self
    {
        $this->instance->setSample($value);
        return $this;
    }

    /**
     * Sets tags field.
     *
     * @param string[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets use cases field.
     *
     * @param string[]|null $value
     */
    public function useCases(?array $value): self
    {
        $this->instance->setUseCases($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Model V1 Response One Of 1 Metadata object.
     */
    public function build(): GetModelV1ResponseOneOf1Metadata
    {
        return CoreHelper::clone($this->instance);
    }
}
