<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\GetModelV1Response0;

/**
 * Builder for model GetModelV1Response0
 *
 * @see GetModelV1Response0
 */
class GetModelV1Response0Builder
{
    /**
     * @var GetModelV1Response0
     */
    private $instance;

    private function __construct(GetModelV1Response0 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Model V1 Response 0 Builder object.
     */
    public static function init(): self
    {
        return new self(new GetModelV1Response0());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets canonical name field.
     *
     * @param string|null $value
     */
    public function canonicalName(?string $value): self
    {
        $this->instance->setCanonicalName($value);
        return $this;
    }

    /**
     * Sets architecture field.
     *
     * @param string|null $value
     */
    public function architecture(?string $value): self
    {
        $this->instance->setArchitecture($value);
        return $this;
    }

    /**
     * Sets languages field.
     *
     * @param string[]|null $value
     */
    public function languages(?array $value): self
    {
        $this->instance->setLanguages($value);
        return $this;
    }

    /**
     * Sets version field.
     *
     * @param string|null $value
     */
    public function version(?string $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Sets uuid field.
     *
     * @param string|null $value
     */
    public function uuid(?string $value): self
    {
        $this->instance->setUuid($value);
        return $this;
    }

    /**
     * Sets batch field.
     *
     * @param bool|null $value
     */
    public function batch(?bool $value): self
    {
        $this->instance->setBatch($value);
        return $this;
    }

    /**
     * Sets streaming field.
     *
     * @param bool|null $value
     */
    public function streaming(?bool $value): self
    {
        $this->instance->setStreaming($value);
        return $this;
    }

    /**
     * Sets formatted output field.
     *
     * @param bool|null $value
     */
    public function formattedOutput(?bool $value): self
    {
        $this->instance->setFormattedOutput($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Model V1 Response 0 object.
     */
    public function build(): GetModelV1Response0
    {
        return CoreHelper::clone($this->instance);
    }
}
