<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\GetProjectKeyV1ResponseItem;
use DeepgramLib\Models\GetProjectKeyV1ResponseItemMember;

/**
 * Builder for model GetProjectKeyV1ResponseItem
 *
 * @see GetProjectKeyV1ResponseItem
 */
class GetProjectKeyV1ResponseItemBuilder
{
    /**
     * @var GetProjectKeyV1ResponseItem
     */
    private $instance;

    private function __construct(GetProjectKeyV1ResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Project Key V1 Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new GetProjectKeyV1ResponseItem());
    }

    /**
     * Sets member field.
     *
     * @param GetProjectKeyV1ResponseItemMember|null $value
     */
    public function member(?GetProjectKeyV1ResponseItemMember $value): self
    {
        $this->instance->setMember($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Project Key V1 Response Item object.
     */
    public function build(): GetProjectKeyV1ResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
