<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\GetProjectKeyV1Response;
use RestApiLib\Models\GetProjectKeyV1ResponseItem;

/**
 * Builder for model GetProjectKeyV1Response
 *
 * @see GetProjectKeyV1Response
 */
class GetProjectKeyV1ResponseBuilder
{
    /**
     * @var GetProjectKeyV1Response
     */
    private $instance;

    private function __construct(GetProjectKeyV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Project Key V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetProjectKeyV1Response());
    }

    /**
     * Sets item field.
     *
     * @param GetProjectKeyV1ResponseItem|null $value
     */
    public function item(?GetProjectKeyV1ResponseItem $value): self
    {
        $this->instance->setItem($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Project Key V1 Response object.
     */
    public function build(): GetProjectKeyV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
