<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\GetProjectDistributionCredentialsV1ResponseDistributionCredentials;

/**
 * Builder for model GetProjectDistributionCredentialsV1ResponseDistributionCredentials
 *
 * @see GetProjectDistributionCredentialsV1ResponseDistributionCredentials
 */
class GetProjectDistributionCredentialsV1ResponseDistributionCredentialsBuilder
{
    /**
     * @var GetProjectDistributionCredentialsV1ResponseDistributionCredentials
     */
    private $instance;

    private function __construct(GetProjectDistributionCredentialsV1ResponseDistributionCredentials $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Project Distribution Credentials V1 Response Distribution Credentials Builder
     * object.
     *
     * @param string $distributionCredentialsId
     * @param string $provider
     * @param string[] $scopes
     * @param \DateTime $created
     */
    public static function init(
        string $distributionCredentialsId,
        string $provider,
        array $scopes,
        \DateTime $created
    ): self {
        return new self(new GetProjectDistributionCredentialsV1ResponseDistributionCredentials(
            $distributionCredentialsId,
            $provider,
            $scopes,
            $created
        ));
    }

    /**
     * Sets comment field.
     *
     * @param string|null $value
     */
    public function comment(?string $value): self
    {
        $this->instance->setComment($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Project Distribution Credentials V1 Response Distribution Credentials object.
     */
    public function build(): GetProjectDistributionCredentialsV1ResponseDistributionCredentials
    {
        return CoreHelper::clone($this->instance);
    }
}
