<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\GetProjectDistributionCredentialsV1Response;
use RestApiLib\Models\GetProjectDistributionCredentialsV1ResponseDistributionCredentials;
use RestApiLib\Models\GetProjectDistributionCredentialsV1ResponseMember;

/**
 * Builder for model GetProjectDistributionCredentialsV1Response
 *
 * @see GetProjectDistributionCredentialsV1Response
 */
class GetProjectDistributionCredentialsV1ResponseBuilder
{
    /**
     * @var GetProjectDistributionCredentialsV1Response
     */
    private $instance;

    private function __construct(GetProjectDistributionCredentialsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Project Distribution Credentials V1 Response Builder object.
     *
     * @param GetProjectDistributionCredentialsV1ResponseMember $member
     * @param GetProjectDistributionCredentialsV1ResponseDistributionCredentials $distributionCredentials
     */
    public static function init(
        GetProjectDistributionCredentialsV1ResponseMember $member,
        GetProjectDistributionCredentialsV1ResponseDistributionCredentials $distributionCredentials
    ): self {
        return new self(new GetProjectDistributionCredentialsV1Response($member, $distributionCredentials));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Project Distribution Credentials V1 Response object.
     */
    public function build(): GetProjectDistributionCredentialsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
