<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\GetProjectKeyV1ResponseItemMember;
use RestApiLib\Models\GetProjectKeyV1ResponseItemMemberApiKey;

/**
 * Builder for model GetProjectKeyV1ResponseItemMember
 *
 * @see GetProjectKeyV1ResponseItemMember
 */
class GetProjectKeyV1ResponseItemMemberBuilder
{
    /**
     * @var GetProjectKeyV1ResponseItemMember
     */
    private $instance;

    private function __construct(GetProjectKeyV1ResponseItemMember $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Project Key V1 Response Item Member Builder object.
     */
    public static function init(): self
    {
        return new self(new GetProjectKeyV1ResponseItemMember());
    }

    /**
     * Sets member id field.
     *
     * @param string|null $value
     */
    public function memberId(?string $value): self
    {
        $this->instance->setMemberId($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets first name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets last name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets api key field.
     *
     * @param GetProjectKeyV1ResponseItemMemberApiKey|null $value
     */
    public function apiKey(?GetProjectKeyV1ResponseItemMemberApiKey $value): self
    {
        $this->instance->setApiKey($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Project Key V1 Response Item Member object.
     */
    public function build(): GetProjectKeyV1ResponseItemMember
    {
        return CoreHelper::clone($this->instance);
    }
}
