<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\GetProjectDistributionCredentialsV1ResponseMember;

/**
 * Builder for model GetProjectDistributionCredentialsV1ResponseMember
 *
 * @see GetProjectDistributionCredentialsV1ResponseMember
 */
class GetProjectDistributionCredentialsV1ResponseMemberBuilder
{
    /**
     * @var GetProjectDistributionCredentialsV1ResponseMember
     */
    private $instance;

    private function __construct(GetProjectDistributionCredentialsV1ResponseMember $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Get Project Distribution Credentials V1 Response Member Builder object.
     *
     * @param string $memberId
     * @param string $email
     */
    public static function init(string $memberId, string $email): self
    {
        return new self(new GetProjectDistributionCredentialsV1ResponseMember($memberId, $email));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Get Project Distribution Credentials V1 Response Member object.
     */
    public function build(): GetProjectDistributionCredentialsV1ResponseMember
    {
        return CoreHelper::clone($this->instance);
    }
}
