<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\GrantV1Request;

/**
 * Builder for model GrantV1Request
 *
 * @see GrantV1Request
 */
class GrantV1RequestBuilder
{
    /**
     * @var GrantV1Request
     */
    private $instance;

    private function __construct(GrantV1Request $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Grant V1 Request Builder object.
     */
    public static function init(): self
    {
        return new self(new GrantV1Request());
    }

    /**
     * Sets ttl seconds field.
     *
     * @param float|null $value
     */
    public function ttlSeconds(?float $value): self
    {
        $this->instance->setTtlSeconds($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Grant V1 Request object.
     */
    public function build(): GrantV1Request
    {
        return CoreHelper::clone($this->instance);
    }
}
