<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\GrantV1Response;

/**
 * Builder for model GrantV1Response
 *
 * @see GrantV1Response
 */
class GrantV1ResponseBuilder
{
    /**
     * @var GrantV1Response
     */
    private $instance;

    private function __construct(GrantV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Grant V1 Response Builder object.
     *
     * @param string $accessToken
     */
    public static function init(string $accessToken): self
    {
        return new self(new GrantV1Response($accessToken));
    }

    /**
     * Sets expires in field.
     *
     * @param float|null $value
     */
    public function expiresIn(?float $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Grant V1 Response object.
     */
    public function build(): GrantV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
