<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\LeaveProjectV1Response;

/**
 * Builder for model LeaveProjectV1Response
 *
 * @see LeaveProjectV1Response
 */
class LeaveProjectV1ResponseBuilder
{
    /**
     * @var LeaveProjectV1Response
     */
    private $instance;

    private function __construct(LeaveProjectV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Leave Project V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new LeaveProjectV1Response());
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Leave Project V1 Response object.
     */
    public function build(): LeaveProjectV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
