<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember;

/**
 * Builder for model ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember
 *
 * @see ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember
 */
class ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMemberBuilder
{
    /**
     * @var ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember
     */
    private $instance;

    private function __construct(
        ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember $instance
    ) {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Distribution Credentials V1 Response Distribution Credentials Items
     * Member Builder object.
     *
     * @param string $memberId
     * @param string $email
     */
    public static function init(string $memberId, string $email): self
    {
        return new self(
            new ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember($memberId, $email)
        );
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Distribution Credentials V1 Response Distribution Credentials Items
     * Member object.
     */
    public function build(): ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember
    {
        return CoreHelper::clone($this->instance);
    }
}
