<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListProjectPurchasesV1ResponseOrdersItems;

/**
 * Builder for model ListProjectPurchasesV1ResponseOrdersItems
 *
 * @see ListProjectPurchasesV1ResponseOrdersItems
 */
class ListProjectPurchasesV1ResponseOrdersItemsBuilder
{
    /**
     * @var ListProjectPurchasesV1ResponseOrdersItems
     */
    private $instance;

    private function __construct(ListProjectPurchasesV1ResponseOrdersItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Purchases V1 Response Orders Items Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectPurchasesV1ResponseOrdersItems());
    }

    /**
     * Sets order id field.
     *
     * @param string|null $value
     */
    public function orderId(?string $value): self
    {
        $this->instance->setOrderId($value);
        return $this;
    }

    /**
     * Sets expiration field.
     *
     * @param \DateTime|null $value
     */
    public function expiration(?\DateTime $value): self
    {
        $this->instance->setExpiration($value);
        return $this;
    }

    /**
     * Sets created field.
     *
     * @param \DateTime|null $value
     */
    public function created(?\DateTime $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets units field.
     *
     * @param string|null $value
     */
    public function units(?string $value): self
    {
        $this->instance->setUnits($value);
        return $this;
    }

    /**
     * Sets order type field.
     *
     * @param string|null $value
     */
    public function orderType(?string $value): self
    {
        $this->instance->setOrderType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Purchases V1 Response Orders Items object.
     */
    public function build(): ListProjectPurchasesV1ResponseOrdersItems
    {
        return CoreHelper::clone($this->instance);
    }
}
