<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\AgentConfigurationV1;
use RestApiLib\Models\ListAgentConfigurationsV1Response;

/**
 * Builder for model ListAgentConfigurationsV1Response
 *
 * @see ListAgentConfigurationsV1Response
 */
class ListAgentConfigurationsV1ResponseBuilder
{
    /**
     * @var ListAgentConfigurationsV1Response
     */
    private $instance;

    private function __construct(ListAgentConfigurationsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Agent Configurations V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListAgentConfigurationsV1Response());
    }

    /**
     * Sets agents field.
     *
     * @param AgentConfigurationV1[]|null $value
     */
    public function agents(?array $value): self
    {
        $this->instance->setAgents($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Agent Configurations V1 Response object.
     */
    public function build(): ListAgentConfigurationsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
