<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListProjectMembersV1Response;
use DeepgramLib\Models\ListProjectMembersV1ResponseMembersItems;

/**
 * Builder for model ListProjectMembersV1Response
 *
 * @see ListProjectMembersV1Response
 */
class ListProjectMembersV1ResponseBuilder
{
    /**
     * @var ListProjectMembersV1Response
     */
    private $instance;

    private function __construct(ListProjectMembersV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Members V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectMembersV1Response());
    }

    /**
     * Sets members field.
     *
     * @param ListProjectMembersV1ResponseMembersItems[]|null $value
     */
    public function members(?array $value): self
    {
        $this->instance->setMembers($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Members V1 Response object.
     */
    public function build(): ListProjectMembersV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
