<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListenV1ResponseResults;
use DeepgramLib\Models\ListenV1ResponseResultsChannelsItems;
use DeepgramLib\Models\ListenV1ResponseResultsSummary;
use DeepgramLib\Models\ListenV1ResponseResultsUtterancesItems;
use DeepgramLib\Models\SharedIntents;
use DeepgramLib\Models\SharedSentiments;
use DeepgramLib\Models\SharedTopics;

/**
 * Builder for model ListenV1ResponseResults
 *
 * @see ListenV1ResponseResults
 */
class ListenV1ResponseResultsBuilder
{
    /**
     * @var ListenV1ResponseResults
     */
    private $instance;

    private function __construct(ListenV1ResponseResults $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Builder object.
     *
     * @param ListenV1ResponseResultsChannelsItems[] $channels
     */
    public static function init(array $channels): self
    {
        return new self(new ListenV1ResponseResults($channels));
    }

    /**
     * Sets utterances field.
     *
     * @param ListenV1ResponseResultsUtterancesItems[]|null $value
     */
    public function utterances(?array $value): self
    {
        $this->instance->setUtterances($value);
        return $this;
    }

    /**
     * Sets summary field.
     *
     * @param ListenV1ResponseResultsSummary|null $value
     */
    public function summary(?ListenV1ResponseResultsSummary $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Sets topics field.
     *
     * @param SharedTopics|null $value
     */
    public function topics(?SharedTopics $value): self
    {
        $this->instance->setTopics($value);
        return $this;
    }

    /**
     * Sets intents field.
     *
     * @param SharedIntents|null $value
     */
    public function intents(?SharedIntents $value): self
    {
        $this->instance->setIntents($value);
        return $this;
    }

    /**
     * Sets sentiments field.
     *
     * @param SharedSentiments|null $value
     */
    public function sentiments(?SharedSentiments $value): self
    {
        $this->instance->setSentiments($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results object.
     */
    public function build(): ListenV1ResponseResults
    {
        return CoreHelper::clone($this->instance);
    }
}
