<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems;
use RestApiLib\Models\ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItems;

/**
 * Builder for model ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems
 *
 * @see ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems
 */
class ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsBuilder
{
    /**
     * @var ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems
     */
    private $instance;

    private function __construct(
        ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems $instance
    ) {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Paragraphs Paragraphs
     * Items Builder object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems());
    }

    /**
     * Sets sentences field.
     *
     * @param ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItemsSentencesItems[]|null $value
     */
    public function sentences(?array $value): self
    {
        $this->instance->setSentences($value);
        return $this;
    }

    /**
     * Sets speaker field.
     *
     * @param int|null $value
     */
    public function speaker(?int $value): self
    {
        $this->instance->setSpeaker($value);
        return $this;
    }

    /**
     * Sets num words field.
     *
     * @param int|null $value
     */
    public function numWords(?int $value): self
    {
        $this->instance->setNumWords($value);
        return $this;
    }

    /**
     * Sets start field.
     *
     * @param float|null $value
     */
    public function start(?float $value): self
    {
        $this->instance->setStart($value);
        return $this;
    }

    /**
     * Sets end field.
     *
     * @param float|null $value
     */
    public function end(?float $value): self
    {
        $this->instance->setEnd($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Paragraphs Paragraphs
     * Items object.
     */
    public function build(): ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
