<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs;
use RestApiLib\Models\ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems;

/**
 * Builder for model ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs
 *
 * @see ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs
 */
class ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsBuilder
{
    /**
     * @var ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs
     */
    private $instance;

    private function __construct(ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Paragraphs Builder
     * object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs());
    }

    /**
     * Sets transcript field.
     *
     * @param string|null $value
     */
    public function transcript(?string $value): self
    {
        $this->instance->setTranscript($value);
        return $this;
    }

    /**
     * Sets paragraphs field.
     *
     * @param ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems[]|null $value
     */
    public function paragraphs(?array $value): self
    {
        $this->instance->setParagraphs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Paragraphs object.
     */
    public function build(): ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs
    {
        return CoreHelper::clone($this->instance);
    }
}
