<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems;

/**
 * Builder for model ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems
 *
 * @see ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems
 */
class ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItemsBuilder
{
    /**
     * @var ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems
     */
    private $instance;

    private function __construct(ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Words Items Builder
     * object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems());
    }

    /**
     * Sets word field.
     *
     * @param string|null $value
     */
    public function word(?string $value): self
    {
        $this->instance->setWord($value);
        return $this;
    }

    /**
     * Sets start field.
     *
     * @param float|null $value
     */
    public function start(?float $value): self
    {
        $this->instance->setStart($value);
        return $this;
    }

    /**
     * Sets end field.
     *
     * @param float|null $value
     */
    public function end(?float $value): self
    {
        $this->instance->setEnd($value);
        return $this;
    }

    /**
     * Sets confidence field.
     *
     * @param float|null $value
     */
    public function confidence(?float $value): self
    {
        $this->instance->setConfidence($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Words Items object.
     */
    public function build(): ListenV1ResponseResultsChannelsItemsAlternativesItemsWordsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
