<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListenV1Response;
use RestApiLib\Models\ListenV1ResponseMetadata;
use RestApiLib\Models\ListenV1ResponseResults;

/**
 * Builder for model ListenV1Response
 *
 * @see ListenV1Response
 */
class ListenV1ResponseBuilder
{
    /**
     * @var ListenV1Response
     */
    private $instance;

    private function __construct(ListenV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Builder object.
     *
     * @param ListenV1ResponseMetadata $metadata
     * @param ListenV1ResponseResults $results
     */
    public static function init(ListenV1ResponseMetadata $metadata, ListenV1ResponseResults $results): self
    {
        return new self(new ListenV1Response($metadata, $results));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response object.
     */
    public function build(): ListenV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
