<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems;

/**
 * Builder for model ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems
 *
 * @see ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems
 */
class ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItemsBuilder
{
    /**
     * @var ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems
     */
    private $instance;

    private function __construct(ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Entities Items
     * Builder object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems());
    }

    /**
     * Sets label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Sets raw value field.
     *
     * @param string|null $value
     */
    public function rawValue(?string $value): self
    {
        $this->instance->setRawValue($value);
        return $this;
    }

    /**
     * Sets confidence field.
     *
     * @param float|null $value
     */
    public function confidence(?float $value): self
    {
        $this->instance->setConfidence($value);
        return $this;
    }

    /**
     * Sets start word field.
     *
     * @param float|null $value
     */
    public function startWord(?float $value): self
    {
        $this->instance->setStartWord($value);
        return $this;
    }

    /**
     * Sets end word field.
     *
     * @param float|null $value
     */
    public function endWord(?float $value): self
    {
        $this->instance->setEndWord($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Entities Items object.
     */
    public function build(): ListenV1ResponseResultsChannelsItemsAlternativesItemsEntitiesItems
    {
        return CoreHelper::clone($this->instance);
    }
}
