<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListProjectBalancesV1ResponseBalancesItems;

/**
 * Builder for model ListProjectBalancesV1ResponseBalancesItems
 *
 * @see ListProjectBalancesV1ResponseBalancesItems
 */
class ListProjectBalancesV1ResponseBalancesItemsBuilder
{
    /**
     * @var ListProjectBalancesV1ResponseBalancesItems
     */
    private $instance;

    private function __construct(ListProjectBalancesV1ResponseBalancesItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Balances V1 Response Balances Items Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectBalancesV1ResponseBalancesItems());
    }

    /**
     * Sets balance id field.
     *
     * @param string|null $value
     */
    public function balanceId(?string $value): self
    {
        $this->instance->setBalanceId($value);
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets units field.
     *
     * @param string|null $value
     */
    public function units(?string $value): self
    {
        $this->instance->setUnits($value);
        return $this;
    }

    /**
     * Sets purchase order id field.
     *
     * @param string|null $value
     */
    public function purchaseOrderId(?string $value): self
    {
        $this->instance->setPurchaseOrderId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Balances V1 Response Balances Items object.
     */
    public function build(): ListProjectBalancesV1ResponseBalancesItems
    {
        return CoreHelper::clone($this->instance);
    }
}
