<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems;

/**
 * Builder for model ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems
 *
 * @see ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems
 */
class ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItemsBuilder
{
    /**
     * @var ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems
     */
    private $instance;

    private function __construct(ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Summaries Items
     * Builder object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems());
    }

    /**
     * Sets summary field.
     *
     * @param string|null $value
     */
    public function summary(?string $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Sets start word field.
     *
     * @param float|null $value
     */
    public function startWord(?float $value): self
    {
        $this->instance->setStartWord($value);
        return $this;
    }

    /**
     * Sets end word field.
     *
     * @param float|null $value
     */
    public function endWord(?float $value): self
    {
        $this->instance->setEndWord($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Alternatives Items Summaries Items
     * object.
     */
    public function build(): ListenV1ResponseResultsChannelsItemsAlternativesItemsSummariesItems
    {
        return CoreHelper::clone($this->instance);
    }
}
