<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListProjectRequestsV1Response;
use DeepgramLib\Models\ProjectRequestResponse;

/**
 * Builder for model ListProjectRequestsV1Response
 *
 * @see ListProjectRequestsV1Response
 */
class ListProjectRequestsV1ResponseBuilder
{
    /**
     * @var ListProjectRequestsV1Response
     */
    private $instance;

    private function __construct(ListProjectRequestsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Requests V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectRequestsV1Response());
    }

    /**
     * Sets page field.
     *
     * @param float|null $value
     */
    public function page(?float $value): self
    {
        $this->instance->setPage($value);
        return $this;
    }

    /**
     * Sets limit field.
     *
     * @param float|null $value
     */
    public function limit(?float $value): self
    {
        $this->instance->setLimit($value);
        return $this;
    }

    /**
     * Sets requests field.
     *
     * @param ProjectRequestResponse[]|null $value
     */
    public function requests(?array $value): self
    {
        $this->instance->setRequests($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Requests V1 Response object.
     */
    public function build(): ListProjectRequestsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
