<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListProjectKeysV1Response;
use DeepgramLib\Models\ListProjectKeysV1ResponseApiKeysItems;

/**
 * Builder for model ListProjectKeysV1Response
 *
 * @see ListProjectKeysV1Response
 */
class ListProjectKeysV1ResponseBuilder
{
    /**
     * @var ListProjectKeysV1Response
     */
    private $instance;

    private function __construct(ListProjectKeysV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Keys V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectKeysV1Response());
    }

    /**
     * Sets api keys field.
     *
     * @param ListProjectKeysV1ResponseApiKeysItems[]|null $value
     */
    public function apiKeys(?array $value): self
    {
        $this->instance->setApiKeys($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Keys V1 Response object.
     */
    public function build(): ListProjectKeysV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
