<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListenV1ResponseMetadataSummaryInfo;

/**
 * Builder for model ListenV1ResponseMetadataSummaryInfo
 *
 * @see ListenV1ResponseMetadataSummaryInfo
 */
class ListenV1ResponseMetadataSummaryInfoBuilder
{
    /**
     * @var ListenV1ResponseMetadataSummaryInfo
     */
    private $instance;

    private function __construct(ListenV1ResponseMetadataSummaryInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Metadata Summary Info Builder object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseMetadataSummaryInfo());
    }

    /**
     * Sets model uuid field.
     *
     * @param string|null $value
     */
    public function modelUuid(?string $value): self
    {
        $this->instance->setModelUuid($value);
        return $this;
    }

    /**
     * Sets input tokens field.
     *
     * @param int|null $value
     */
    public function inputTokens(?int $value): self
    {
        $this->instance->setInputTokens($value);
        return $this;
    }

    /**
     * Sets output tokens field.
     *
     * @param int|null $value
     */
    public function outputTokens(?int $value): self
    {
        $this->instance->setOutputTokens($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Metadata Summary Info object.
     */
    public function build(): ListenV1ResponseMetadataSummaryInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
