<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems;
use RestApiLib\Models\ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials;
use RestApiLib\Models\ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember;

/**
 * Builder for model ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems
 *
 * @see ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems
 */
class ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsBuilder
{
    /**
     * @var ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems
     */
    private $instance;

    private function __construct(ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Distribution Credentials V1 Response Distribution Credentials Items
     * Builder object.
     *
     * @param ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember $member
     * @param ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials $distributionCredentials
     */
    public static function init(
        ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsMember $member,
        ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItemsDistributionCredentials $distributionCredentials
    ): self {
        return new self(new ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems(
            $member,
            $distributionCredentials
        ));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Distribution Credentials V1 Response Distribution Credentials Items
     * object.
     */
    public function build(): ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
