<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListModelsV1Response;
use RestApiLib\Models\ListModelsV1ResponseSttModels;
use RestApiLib\Models\ListModelsV1ResponseTtsModels;

/**
 * Builder for model ListModelsV1Response
 *
 * @see ListModelsV1Response
 */
class ListModelsV1ResponseBuilder
{
    /**
     * @var ListModelsV1Response
     */
    private $instance;

    private function __construct(ListModelsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Models V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListModelsV1Response());
    }

    /**
     * Sets stt field.
     *
     * @param ListModelsV1ResponseSttModels[]|null $value
     */
    public function stt(?array $value): self
    {
        $this->instance->setStt($value);
        return $this;
    }

    /**
     * Sets tts field.
     *
     * @param ListModelsV1ResponseTtsModels[]|null $value
     */
    public function tts(?array $value): self
    {
        $this->instance->setTts($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Models V1 Response object.
     */
    public function build(): ListModelsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
