<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListProjectDistributionCredentialsV1Response;
use RestApiLib\Models\ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems;

/**
 * Builder for model ListProjectDistributionCredentialsV1Response
 *
 * @see ListProjectDistributionCredentialsV1Response
 */
class ListProjectDistributionCredentialsV1ResponseBuilder
{
    /**
     * @var ListProjectDistributionCredentialsV1Response
     */
    private $instance;

    private function __construct(ListProjectDistributionCredentialsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Distribution Credentials V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectDistributionCredentialsV1Response());
    }

    /**
     * Sets distribution credentials field.
     *
     * @param ListProjectDistributionCredentialsV1ResponseDistributionCredentialsItems[]|null $value
     */
    public function distributionCredentials(?array $value): self
    {
        $this->instance->setDistributionCredentials($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Distribution Credentials V1 Response object.
     */
    public function build(): ListProjectDistributionCredentialsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
