<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListenV1ResponseResultsChannelsItemsSearchItems;
use DeepgramLib\Models\ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems;

/**
 * Builder for model ListenV1ResponseResultsChannelsItemsSearchItems
 *
 * @see ListenV1ResponseResultsChannelsItemsSearchItems
 */
class ListenV1ResponseResultsChannelsItemsSearchItemsBuilder
{
    /**
     * @var ListenV1ResponseResultsChannelsItemsSearchItems
     */
    private $instance;

    private function __construct(ListenV1ResponseResultsChannelsItemsSearchItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Search Items Builder object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseResultsChannelsItemsSearchItems());
    }

    /**
     * Sets query field.
     *
     * @param string|null $value
     */
    public function query(?string $value): self
    {
        $this->instance->setQuery($value);
        return $this;
    }

    /**
     * Sets hits field.
     *
     * @param ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems[]|null $value
     */
    public function hits(?array $value): self
    {
        $this->instance->setHits($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Search Items object.
     */
    public function build(): ListenV1ResponseResultsChannelsItemsSearchItems
    {
        return CoreHelper::clone($this->instance);
    }
}
