<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListModelsV1ResponseTtsModels;
use DeepgramLib\Models\ListModelsV1ResponseTtsModelsMetadata;

/**
 * Builder for model ListModelsV1ResponseTtsModels
 *
 * @see ListModelsV1ResponseTtsModels
 */
class ListModelsV1ResponseTtsModelsBuilder
{
    /**
     * @var ListModelsV1ResponseTtsModels
     */
    private $instance;

    private function __construct(ListModelsV1ResponseTtsModels $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Models V1 Response Tts Models Builder object.
     */
    public static function init(): self
    {
        return new self(new ListModelsV1ResponseTtsModels());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets canonical name field.
     *
     * @param string|null $value
     */
    public function canonicalName(?string $value): self
    {
        $this->instance->setCanonicalName($value);
        return $this;
    }

    /**
     * Sets architecture field.
     *
     * @param string|null $value
     */
    public function architecture(?string $value): self
    {
        $this->instance->setArchitecture($value);
        return $this;
    }

    /**
     * Sets languages field.
     *
     * @param string[]|null $value
     */
    public function languages(?array $value): self
    {
        $this->instance->setLanguages($value);
        return $this;
    }

    /**
     * Sets version field.
     *
     * @param string|null $value
     */
    public function version(?string $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Sets uuid field.
     *
     * @param string|null $value
     */
    public function uuid(?string $value): self
    {
        $this->instance->setUuid($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param ListModelsV1ResponseTtsModelsMetadata|null $value
     */
    public function metadata(?ListModelsV1ResponseTtsModelsMetadata $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Models V1 Response Tts Models object.
     */
    public function build(): ListModelsV1ResponseTtsModels
    {
        return CoreHelper::clone($this->instance);
    }
}
