<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListenV1AcceptedResponse;

/**
 * Builder for model ListenV1AcceptedResponse
 *
 * @see ListenV1AcceptedResponse
 */
class ListenV1AcceptedResponseBuilder
{
    /**
     * @var ListenV1AcceptedResponse
     */
    private $instance;

    private function __construct(ListenV1AcceptedResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Accepted Response Builder object.
     *
     * @param string $requestId
     */
    public static function init(string $requestId): self
    {
        return new self(new ListenV1AcceptedResponse($requestId));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Accepted Response object.
     */
    public function build(): ListenV1AcceptedResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
