<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListProjectKeysV1ResponseApiKeysItemsMember;

/**
 * Builder for model ListProjectKeysV1ResponseApiKeysItemsMember
 *
 * @see ListProjectKeysV1ResponseApiKeysItemsMember
 */
class ListProjectKeysV1ResponseApiKeysItemsMemberBuilder
{
    /**
     * @var ListProjectKeysV1ResponseApiKeysItemsMember
     */
    private $instance;

    private function __construct(ListProjectKeysV1ResponseApiKeysItemsMember $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Keys V1 Response Api Keys Items Member Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectKeysV1ResponseApiKeysItemsMember());
    }

    /**
     * Sets member id field.
     *
     * @param string|null $value
     */
    public function memberId(?string $value): self
    {
        $this->instance->setMemberId($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Keys V1 Response Api Keys Items Member object.
     */
    public function build(): ListProjectKeysV1ResponseApiKeysItemsMember
    {
        return CoreHelper::clone($this->instance);
    }
}
