<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems;

/**
 * Builder for model ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems
 *
 * @see ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems
 */
class ListenV1ResponseResultsChannelsItemsSearchItemsHitsItemsBuilder
{
    /**
     * @var ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems
     */
    private $instance;

    private function __construct(ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Search Items Hits Items Builder object.
     */
    public static function init(): self
    {
        return new self(new ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems());
    }

    /**
     * Sets confidence field.
     *
     * @param float|null $value
     */
    public function confidence(?float $value): self
    {
        $this->instance->setConfidence($value);
        return $this;
    }

    /**
     * Sets start field.
     *
     * @param float|null $value
     */
    public function start(?float $value): self
    {
        $this->instance->setStart($value);
        return $this;
    }

    /**
     * Sets end field.
     *
     * @param float|null $value
     */
    public function end(?float $value): self
    {
        $this->instance->setEnd($value);
        return $this;
    }

    /**
     * Sets snippet field.
     *
     * @param string|null $value
     */
    public function snippet(?string $value): self
    {
        $this->instance->setSnippet($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Listen V1 Response Results Channels Items Search Items Hits Items object.
     */
    public function build(): ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
