<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ListProjectInvitesV1Response;
use DeepgramLib\Models\ListProjectInvitesV1ResponseInvitesItems;

/**
 * Builder for model ListProjectInvitesV1Response
 *
 * @see ListProjectInvitesV1Response
 */
class ListProjectInvitesV1ResponseBuilder
{
    /**
     * @var ListProjectInvitesV1Response
     */
    private $instance;

    private function __construct(ListProjectInvitesV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Project Invites V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListProjectInvitesV1Response());
    }

    /**
     * Sets invites field.
     *
     * @param ListProjectInvitesV1ResponseInvitesItems[]|null $value
     */
    public function invites(?array $value): self
    {
        $this->instance->setInvites($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Project Invites V1 Response object.
     */
    public function build(): ListProjectInvitesV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
