<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ReadV1ResponseMetadata;
use RestApiLib\Models\ReadV1ResponseMetadataMetadata;

/**
 * Builder for model ReadV1ResponseMetadata
 *
 * @see ReadV1ResponseMetadata
 */
class ReadV1ResponseMetadataBuilder
{
    /**
     * @var ReadV1ResponseMetadata
     */
    private $instance;

    private function __construct(ReadV1ResponseMetadata $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Read V1 Response Metadata Builder object.
     */
    public static function init(): self
    {
        return new self(new ReadV1ResponseMetadata());
    }

    /**
     * Sets metadata field.
     *
     * @param ReadV1ResponseMetadataMetadata|null $value
     */
    public function metadata(?ReadV1ResponseMetadataMetadata $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Read V1 Response Metadata object.
     */
    public function build(): ReadV1ResponseMetadata
    {
        return CoreHelper::clone($this->instance);
    }
}
