<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ReadV1ResponseMetadataMetadataSentimentInfo;

/**
 * Builder for model ReadV1ResponseMetadataMetadataSentimentInfo
 *
 * @see ReadV1ResponseMetadataMetadataSentimentInfo
 */
class ReadV1ResponseMetadataMetadataSentimentInfoBuilder
{
    /**
     * @var ReadV1ResponseMetadataMetadataSentimentInfo
     */
    private $instance;

    private function __construct(ReadV1ResponseMetadataMetadataSentimentInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Read V1 Response Metadata Metadata Sentiment Info Builder object.
     */
    public static function init(): self
    {
        return new self(new ReadV1ResponseMetadataMetadataSentimentInfo());
    }

    /**
     * Sets model uuid field.
     *
     * @param string|null $value
     */
    public function modelUuid(?string $value): self
    {
        $this->instance->setModelUuid($value);
        return $this;
    }

    /**
     * Sets input tokens field.
     *
     * @param int|null $value
     */
    public function inputTokens(?int $value): self
    {
        $this->instance->setInputTokens($value);
        return $this;
    }

    /**
     * Sets output tokens field.
     *
     * @param int|null $value
     */
    public function outputTokens(?int $value): self
    {
        $this->instance->setOutputTokens($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Read V1 Response Metadata Metadata Sentiment Info object.
     */
    public function build(): ReadV1ResponseMetadataMetadataSentimentInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
