<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ReadV1RequestUrl;

/**
 * Builder for model ReadV1RequestUrl
 *
 * @see ReadV1RequestUrl
 */
class ReadV1RequestUrlBuilder
{
    /**
     * @var ReadV1RequestUrl
     */
    private $instance;

    private function __construct(ReadV1RequestUrl $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Read V1 Request Url Builder object.
     *
     * @param string $url
     */
    public static function init(string $url): self
    {
        return new self(new ReadV1RequestUrl($url));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Read V1 Request Url object.
     */
    public function build(): ReadV1RequestUrl
    {
        return CoreHelper::clone($this->instance);
    }
}
