<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\ReadV1ResponseResultsSummary;
use RestApiLib\Models\ReadV1ResponseResultsSummaryResults;

/**
 * Builder for model ReadV1ResponseResultsSummary
 *
 * @see ReadV1ResponseResultsSummary
 */
class ReadV1ResponseResultsSummaryBuilder
{
    /**
     * @var ReadV1ResponseResultsSummary
     */
    private $instance;

    private function __construct(ReadV1ResponseResultsSummary $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Read V1 Response Results Summary Builder object.
     */
    public static function init(): self
    {
        return new self(new ReadV1ResponseResultsSummary());
    }

    /**
     * Sets results field.
     *
     * @param ReadV1ResponseResultsSummaryResults|null $value
     */
    public function results(?ReadV1ResponseResultsSummaryResults $value): self
    {
        $this->instance->setResults($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Read V1 Response Results Summary object.
     */
    public function build(): ReadV1ResponseResultsSummary
    {
        return CoreHelper::clone($this->instance);
    }
}
