<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ReadV1ResponseResults;
use DeepgramLib\Models\ReadV1ResponseResultsSummary;
use DeepgramLib\Models\SharedIntents;
use DeepgramLib\Models\SharedSentiments;
use DeepgramLib\Models\SharedTopics;

/**
 * Builder for model ReadV1ResponseResults
 *
 * @see ReadV1ResponseResults
 */
class ReadV1ResponseResultsBuilder
{
    /**
     * @var ReadV1ResponseResults
     */
    private $instance;

    private function __construct(ReadV1ResponseResults $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Read V1 Response Results Builder object.
     */
    public static function init(): self
    {
        return new self(new ReadV1ResponseResults());
    }

    /**
     * Sets summary field.
     *
     * @param ReadV1ResponseResultsSummary|null $value
     */
    public function summary(?ReadV1ResponseResultsSummary $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Sets topics field.
     *
     * @param SharedTopics|null $value
     */
    public function topics(?SharedTopics $value): self
    {
        $this->instance->setTopics($value);
        return $this;
    }

    /**
     * Sets intents field.
     *
     * @param SharedIntents|null $value
     */
    public function intents(?SharedIntents $value): self
    {
        $this->instance->setIntents($value);
        return $this;
    }

    /**
     * Sets sentiments field.
     *
     * @param SharedSentiments|null $value
     */
    public function sentiments(?SharedSentiments $value): self
    {
        $this->instance->setSentiments($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Read V1 Response Results object.
     */
    public function build(): ReadV1ResponseResults
    {
        return CoreHelper::clone($this->instance);
    }
}
