<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\ReadV1ResponseResultsSummaryResults;
use DeepgramLib\Models\ReadV1ResponseResultsSummaryResultsSummary;

/**
 * Builder for model ReadV1ResponseResultsSummaryResults
 *
 * @see ReadV1ResponseResultsSummaryResults
 */
class ReadV1ResponseResultsSummaryResultsBuilder
{
    /**
     * @var ReadV1ResponseResultsSummaryResults
     */
    private $instance;

    private function __construct(ReadV1ResponseResultsSummaryResults $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Read V1 Response Results Summary Results Builder object.
     */
    public static function init(): self
    {
        return new self(new ReadV1ResponseResultsSummaryResults());
    }

    /**
     * Sets summary field.
     *
     * @param ReadV1ResponseResultsSummaryResultsSummary|null $value
     */
    public function summary(?ReadV1ResponseResultsSummaryResultsSummary $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Read V1 Response Results Summary Results object.
     */
    public function build(): ReadV1ResponseResultsSummaryResults
    {
        return CoreHelper::clone($this->instance);
    }
}
