<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\SharedIntentsResultsIntentsSegmentsItems;
use DeepgramLib\Models\SharedIntentsResultsIntentsSegmentsItemsIntentsItems;

/**
 * Builder for model SharedIntentsResultsIntentsSegmentsItems
 *
 * @see SharedIntentsResultsIntentsSegmentsItems
 */
class SharedIntentsResultsIntentsSegmentsItemsBuilder
{
    /**
     * @var SharedIntentsResultsIntentsSegmentsItems
     */
    private $instance;

    private function __construct(SharedIntentsResultsIntentsSegmentsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shared Intents Results Intents Segments Items Builder object.
     */
    public static function init(): self
    {
        return new self(new SharedIntentsResultsIntentsSegmentsItems());
    }

    /**
     * Sets text field.
     *
     * @param string|null $value
     */
    public function text(?string $value): self
    {
        $this->instance->setText($value);
        return $this;
    }

    /**
     * Sets start word field.
     *
     * @param float|null $value
     */
    public function startWord(?float $value): self
    {
        $this->instance->setStartWord($value);
        return $this;
    }

    /**
     * Sets end word field.
     *
     * @param float|null $value
     */
    public function endWord(?float $value): self
    {
        $this->instance->setEndWord($value);
        return $this;
    }

    /**
     * Sets intents field.
     *
     * @param SharedIntentsResultsIntentsSegmentsItemsIntentsItems[]|null $value
     */
    public function intents(?array $value): self
    {
        $this->instance->setIntents($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shared Intents Results Intents Segments Items object.
     */
    public function build(): SharedIntentsResultsIntentsSegmentsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
