<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\SharedTopicsResultsTopics;
use DeepgramLib\Models\SharedTopicsResultsTopicsSegmentsItems;

/**
 * Builder for model SharedTopicsResultsTopics
 *
 * @see SharedTopicsResultsTopics
 */
class SharedTopicsResultsTopicsBuilder
{
    /**
     * @var SharedTopicsResultsTopics
     */
    private $instance;

    private function __construct(SharedTopicsResultsTopics $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shared Topics Results Topics Builder object.
     */
    public static function init(): self
    {
        return new self(new SharedTopicsResultsTopics());
    }

    /**
     * Sets segments field.
     *
     * @param SharedTopicsResultsTopicsSegmentsItems[]|null $value
     */
    public function segments(?array $value): self
    {
        $this->instance->setSegments($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shared Topics Results Topics object.
     */
    public function build(): SharedTopicsResultsTopics
    {
        return CoreHelper::clone($this->instance);
    }
}
