<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\SharedIntentsResults;
use DeepgramLib\Models\SharedIntentsResultsIntents;

/**
 * Builder for model SharedIntentsResults
 *
 * @see SharedIntentsResults
 */
class SharedIntentsResultsBuilder
{
    /**
     * @var SharedIntentsResults
     */
    private $instance;

    private function __construct(SharedIntentsResults $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shared Intents Results Builder object.
     */
    public static function init(): self
    {
        return new self(new SharedIntentsResults());
    }

    /**
     * Sets intents field.
     *
     * @param SharedIntentsResultsIntents|null $value
     */
    public function intents(?SharedIntentsResultsIntents $value): self
    {
        $this->instance->setIntents($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shared Intents Results object.
     */
    public function build(): SharedIntentsResults
    {
        return CoreHelper::clone($this->instance);
    }
}
