<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\SharedIntentsResultsIntents;
use RestApiLib\Models\SharedIntentsResultsIntentsSegmentsItems;

/**
 * Builder for model SharedIntentsResultsIntents
 *
 * @see SharedIntentsResultsIntents
 */
class SharedIntentsResultsIntentsBuilder
{
    /**
     * @var SharedIntentsResultsIntents
     */
    private $instance;

    private function __construct(SharedIntentsResultsIntents $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shared Intents Results Intents Builder object.
     */
    public static function init(): self
    {
        return new self(new SharedIntentsResultsIntents());
    }

    /**
     * Sets segments field.
     *
     * @param SharedIntentsResultsIntentsSegmentsItems[]|null $value
     */
    public function segments(?array $value): self
    {
        $this->instance->setSegments($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shared Intents Results Intents object.
     */
    public function build(): SharedIntentsResultsIntents
    {
        return CoreHelper::clone($this->instance);
    }
}
