<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use RestApiLib\Models\SharedTopicsResultsTopicsSegmentsItemsTopicsItems;

/**
 * Builder for model SharedTopicsResultsTopicsSegmentsItemsTopicsItems
 *
 * @see SharedTopicsResultsTopicsSegmentsItemsTopicsItems
 */
class SharedTopicsResultsTopicsSegmentsItemsTopicsItemsBuilder
{
    /**
     * @var SharedTopicsResultsTopicsSegmentsItemsTopicsItems
     */
    private $instance;

    private function __construct(SharedTopicsResultsTopicsSegmentsItemsTopicsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shared Topics Results Topics Segments Items Topics Items Builder object.
     */
    public static function init(): self
    {
        return new self(new SharedTopicsResultsTopicsSegmentsItemsTopicsItems());
    }

    /**
     * Sets topic field.
     *
     * @param string|null $value
     */
    public function topic(?string $value): self
    {
        $this->instance->setTopic($value);
        return $this;
    }

    /**
     * Sets confidence score field.
     *
     * @param float|null $value
     */
    public function confidenceScore(?float $value): self
    {
        $this->instance->setConfidenceScore($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shared Topics Results Topics Segments Items Topics Items object.
     */
    public function build(): SharedTopicsResultsTopicsSegmentsItemsTopicsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
