<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\SharedSentimentsAverage;

/**
 * Builder for model SharedSentimentsAverage
 *
 * @see SharedSentimentsAverage
 */
class SharedSentimentsAverageBuilder
{
    /**
     * @var SharedSentimentsAverage
     */
    private $instance;

    private function __construct(SharedSentimentsAverage $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shared Sentiments Average Builder object.
     */
    public static function init(): self
    {
        return new self(new SharedSentimentsAverage());
    }

    /**
     * Sets sentiment field.
     *
     * @param string|null $value
     */
    public function sentiment(?string $value): self
    {
        $this->instance->setSentiment($value);
        return $this;
    }

    /**
     * Sets sentiment score field.
     *
     * @param float|null $value
     */
    public function sentimentScore(?float $value): self
    {
        $this->instance->setSentimentScore($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shared Sentiments Average object.
     */
    public function build(): SharedSentimentsAverage
    {
        return CoreHelper::clone($this->instance);
    }
}
