<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\SharedIntents;
use DeepgramLib\Models\SharedIntentsResults;

/**
 * Builder for model SharedIntents
 *
 * @see SharedIntents
 */
class SharedIntentsBuilder
{
    /**
     * @var SharedIntents
     */
    private $instance;

    private function __construct(SharedIntents $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Shared Intents Builder object.
     */
    public static function init(): self
    {
        return new self(new SharedIntents());
    }

    /**
     * Sets results field.
     *
     * @param SharedIntentsResults|null $value
     */
    public function results(?SharedIntentsResults $value): self
    {
        $this->instance->setResults($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Shared Intents object.
     */
    public function build(): SharedIntents
    {
        return CoreHelper::clone($this->instance);
    }
}
