<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\SpeakV2AcceptedResponse;

/**
 * Builder for model SpeakV2AcceptedResponse
 *
 * @see SpeakV2AcceptedResponse
 */
class SpeakV2AcceptedResponseBuilder
{
    /**
     * @var SpeakV2AcceptedResponse
     */
    private $instance;

    private function __construct(SpeakV2AcceptedResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Speak V2 Accepted Response Builder object.
     *
     * @param string $requestId
     */
    public static function init(string $requestId): self
    {
        return new self(new SpeakV2AcceptedResponse($requestId));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Speak V2 Accepted Response object.
     */
    public function build(): SpeakV2AcceptedResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
