<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\UpdateAgentMetadataV1Request;

/**
 * Builder for model UpdateAgentMetadataV1Request
 *
 * @see UpdateAgentMetadataV1Request
 */
class UpdateAgentMetadataV1RequestBuilder
{
    /**
     * @var UpdateAgentMetadataV1Request
     */
    private $instance;

    private function __construct(UpdateAgentMetadataV1Request $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Agent Metadata V1 Request Builder object.
     *
     * @param array<string,string> $metadata
     */
    public static function init(array $metadata): self
    {
        return new self(new UpdateAgentMetadataV1Request($metadata));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Update Agent Metadata V1 Request object.
     */
    public function build(): UpdateAgentMetadataV1Request
    {
        return CoreHelper::clone($this->instance);
    }
}
