<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\UpdateProjectV1Request;

/**
 * Builder for model UpdateProjectV1Request
 *
 * @see UpdateProjectV1Request
 */
class UpdateProjectV1RequestBuilder
{
    /**
     * @var UpdateProjectV1Request
     */
    private $instance;

    private function __construct(UpdateProjectV1Request $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Project V1 Request Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateProjectV1Request());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Update Project V1 Request object.
     */
    public function build(): UpdateProjectV1Request
    {
        return CoreHelper::clone($this->instance);
    }
}
