<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\UsageFieldsV1Response;
use DeepgramLib\Models\UsageFieldsV1ResponseModelsItems;

/**
 * Builder for model UsageFieldsV1Response
 *
 * @see UsageFieldsV1Response
 */
class UsageFieldsV1ResponseBuilder
{
    /**
     * @var UsageFieldsV1Response
     */
    private $instance;

    private function __construct(UsageFieldsV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Usage Fields V1 Response Builder object.
     */
    public static function init(): self
    {
        return new self(new UsageFieldsV1Response());
    }

    /**
     * Sets tags field.
     *
     * @param string[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets models field.
     *
     * @param UsageFieldsV1ResponseModelsItems[]|null $value
     */
    public function models(?array $value): self
    {
        $this->instance->setModels($value);
        return $this;
    }

    /**
     * Sets processing methods field.
     *
     * @param string[]|null $value
     */
    public function processingMethods(?array $value): self
    {
        $this->instance->setProcessingMethods($value);
        return $this;
    }

    /**
     * Sets features field.
     *
     * @param string[]|null $value
     */
    public function features(?array $value): self
    {
        $this->instance->setFeatures($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Usage Fields V1 Response object.
     */
    public function build(): UsageFieldsV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
