<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\UsageFieldsV1ResponseModelsItems;

/**
 * Builder for model UsageFieldsV1ResponseModelsItems
 *
 * @see UsageFieldsV1ResponseModelsItems
 */
class UsageFieldsV1ResponseModelsItemsBuilder
{
    /**
     * @var UsageFieldsV1ResponseModelsItems
     */
    private $instance;

    private function __construct(UsageFieldsV1ResponseModelsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Usage Fields V1 Response Models Items Builder object.
     */
    public static function init(): self
    {
        return new self(new UsageFieldsV1ResponseModelsItems());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets language field.
     *
     * @param string|null $value
     */
    public function language(?string $value): self
    {
        $this->instance->setLanguage($value);
        return $this;
    }

    /**
     * Sets version field.
     *
     * @param string|null $value
     */
    public function version(?string $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Sets model id field.
     *
     * @param string|null $value
     */
    public function modelId(?string $value): self
    {
        $this->instance->setModelId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Usage Fields V1 Response Models Items object.
     */
    public function build(): UsageFieldsV1ResponseModelsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
