<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\UsageBreakdownV1Response;
use DeepgramLib\Models\UsageBreakdownV1ResponseResolution;
use DeepgramLib\Models\UsageBreakdownV1ResponseResultsItems;

/**
 * Builder for model UsageBreakdownV1Response
 *
 * @see UsageBreakdownV1Response
 */
class UsageBreakdownV1ResponseBuilder
{
    /**
     * @var UsageBreakdownV1Response
     */
    private $instance;

    private function __construct(UsageBreakdownV1Response $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Usage Breakdown V1 Response Builder object.
     *
     * @param \DateTime $start
     * @param \DateTime $end
     * @param UsageBreakdownV1ResponseResolution $resolution
     * @param UsageBreakdownV1ResponseResultsItems[] $results
     */
    public static function init(
        \DateTime $start,
        \DateTime $end,
        UsageBreakdownV1ResponseResolution $resolution,
        array $results
    ): self {
        return new self(new UsageBreakdownV1Response($start, $end, $resolution, $results));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Usage Breakdown V1 Response object.
     */
    public function build(): UsageBreakdownV1Response
    {
        return CoreHelper::clone($this->instance);
    }
}
