<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models\Builders;

use Core\Utils\CoreHelper;
use DeepgramLib\Models\UsageV1ResponseResolution;

/**
 * Builder for model UsageV1ResponseResolution
 *
 * @see UsageV1ResponseResolution
 */
class UsageV1ResponseResolutionBuilder
{
    /**
     * @var UsageV1ResponseResolution
     */
    private $instance;

    private function __construct(UsageV1ResponseResolution $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Usage V1 Response Resolution Builder object.
     */
    public static function init(): self
    {
        return new self(new UsageV1ResponseResolution());
    }

    /**
     * Sets units field.
     *
     * @param string|null $value
     */
    public function units(?string $value): self
    {
        $this->instance->setUnits($value);
        return $this;
    }

    /**
     * Sets amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Usage V1 Response Resolution object.
     */
    public function build(): UsageV1ResponseResolution
    {
        return CoreHelper::clone($this->instance);
    }
}
