<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use DeepgramLib\Utils\DateTimeHelper;
use stdClass;

/**
 * A template variable for agent configurations
 */
class AgentVariableV1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $variableId;

    /**
     * @var string
     */
    private $key;

    /**
     * @var array
     */
    private $value;

    /**
     * @var \DateTime|null
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     */
    private $updatedAt;

    /**
     * @param string $variableId
     * @param string $key
     * @param array $value
     */
    public function __construct(string $variableId, string $key, array $value)
    {
        $this->variableId = $variableId;
        $this->key = $key;
        $this->value = $value;
    }

    /**
     * Returns Variable Id.
     * The unique identifier of the variable
     */
    public function getVariableId(): string
    {
        return $this->variableId;
    }

    /**
     * Sets Variable Id.
     * The unique identifier of the variable
     *
     * @required
     * @maps variable_id
     */
    public function setVariableId(string $variableId): void
    {
        $this->variableId = $variableId;
    }

    /**
     * Returns Key.
     * The variable name, following the DG_<VARIABLE_NAME> format
     */
    public function getKey(): string
    {
        return $this->key;
    }

    /**
     * Sets Key.
     * The variable name, following the DG_<VARIABLE_NAME> format
     *
     * @required
     * @maps key
     */
    public function setKey(string $key): void
    {
        $this->key = $key;
    }

    /**
     * Returns Value.
     * The value to substitute. Can be any valid JSON type
     */
    public function getValue(): array
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * The value to substitute. Can be any valid JSON type
     *
     * @required
     * @maps value
     */
    public function setValue(array $value): void
    {
        $this->value = $value;
    }

    /**
     * Returns Created At.
     * Timestamp when the variable was created
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * Timestamp when the variable was created
     *
     * @maps created_at
     * @factory \DeepgramLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     * Timestamp when the variable was last updated
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     * Timestamp when the variable was last updated
     *
     * @maps updated_at
     * @factory \DeepgramLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Converts the AgentVariableV1 object to a human-readable string representation.
     *
     * @return string The string representation of the AgentVariableV1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AgentVariableV1',
            [
                'variableId' => $this->variableId,
                'key' => $this->key,
                'value' => $this->value,
                'createdAt' => $this->createdAt,
                'updatedAt' => $this->updatedAt,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['variable_id', 'key', 'value', 'created_at', 'updated_at'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['variable_id']    = $this->variableId;
        $json['key']            = $this->key;
        $json['value']          = $this->value;
        if (isset($this->createdAt)) {
            $json['created_at'] = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        }
        if (isset($this->updatedAt)) {
            $json['updated_at'] = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
