<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

/**
 * OpenAI models
 */
class AgentThinkModelsV1ResponseModelsItems0 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var array
     */
    private $provider;

    /**
     * @param string $id
     * @param string $name
     * @param array $provider
     */
    public function __construct(string $id, string $name, array $provider)
    {
        $this->id = $id;
        $this->name = $name;
        $this->provider = $provider;
    }

    /**
     * Returns Id.
     * The unique identifier of the OpenAI model
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The unique identifier of the OpenAI model
     *
     * @required
     * @maps id
     * @factory \DeepgramLib\Models\AgentThinkModelsV1ResponseModelsItemsOneOf0Id::checkValue
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Name.
     * The display name of the model
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The display name of the model
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Provider.
     * The provider of the model
     */
    public function getProvider(): array
    {
        return $this->provider;
    }

    /**
     * Sets Provider.
     * The provider of the model
     *
     * @required
     * @maps provider
     */
    public function setProvider(array $provider): void
    {
        $this->provider = $provider;
    }

    /**
     * Converts the AgentThinkModelsV1ResponseModelsItems0 object to a human-readable string representation.
     *
     * @return string The string representation of the AgentThinkModelsV1ResponseModelsItems0 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AgentThinkModelsV1ResponseModelsItems0',
            [
                'id' => $this->id,
                'name' => $this->name,
                'provider' => $this->provider,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['id', 'name', 'provider'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']       = AgentThinkModelsV1ResponseModelsItemsOneOf0Id::checkValue($this->id);
        $json['name']     = $this->name;
        $json['provider'] = $this->provider;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
