<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use RestApiLib\Utils\DateTimeHelper;
use stdClass;

/**
 * A reusable agent configuration
 */
class AgentConfigurationV1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $agentId;

    /**
     * @var array
     */
    private $config;

    /**
     * @var array<string,string>|null
     */
    private $metadata;

    /**
     * @var \DateTime|null
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     */
    private $updatedAt;

    /**
     * @param string $agentId
     * @param array $config
     */
    public function __construct(string $agentId, array $config)
    {
        $this->agentId = $agentId;
        $this->config = $config;
    }

    /**
     * Returns Agent Id.
     * The unique identifier of the agent configuration
     */
    public function getAgentId(): string
    {
        return $this->agentId;
    }

    /**
     * Sets Agent Id.
     * The unique identifier of the agent configuration
     *
     * @required
     * @maps agent_id
     */
    public function setAgentId(string $agentId): void
    {
        $this->agentId = $agentId;
    }

    /**
     * Returns Config.
     * The agent configuration object
     */
    public function getConfig(): array
    {
        return $this->config;
    }

    /**
     * Sets Config.
     * The agent configuration object
     *
     * @required
     * @maps config
     */
    public function setConfig(array $config): void
    {
        $this->config = $config;
    }

    /**
     * Returns Metadata.
     * A map of arbitrary key-value pairs for labeling or organizing the agent configuration
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     * A map of arbitrary key-value pairs for labeling or organizing the agent configuration
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Created At.
     * Timestamp when the configuration was created
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     * Timestamp when the configuration was created
     *
     * @maps created_at
     * @factory \RestApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(?\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     * Timestamp when the configuration was last updated
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     * Timestamp when the configuration was last updated
     *
     * @maps updated_at
     * @factory \RestApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(?\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Converts the AgentConfigurationV1 object to a human-readable string representation.
     *
     * @return string The string representation of the AgentConfigurationV1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AgentConfigurationV1',
            [
                'agentId' => $this->agentId,
                'config' => $this->config,
                'metadata' => $this->metadata,
                'createdAt' => $this->createdAt,
                'updatedAt' => $this->updatedAt,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['agent_id', 'config', 'metadata', 'created_at', 'updated_at'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['agent_id']       = $this->agentId;
        $json['config']         = $this->config;
        if (isset($this->metadata)) {
            $json['metadata']   = $this->metadata;
        }
        if (isset($this->createdAt)) {
            $json['created_at'] = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        }
        if (isset($this->updatedAt)) {
            $json['updated_at'] = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
