<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use RestApiLib\Utils\DateTimeHelper;
use stdClass;

class BillingBreakdownV1ResponseResultsItemsGrouping implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $start;

    /**
     * @var \DateTime|null
     */
    private $end;

    /**
     * @var array
     */
    private $accessor = [];

    /**
     * @var array
     */
    private $deployment = [];

    /**
     * @var array
     */
    private $lineItem = [];

    /**
     * @var array
     */
    private $tags = [];

    /**
     * Returns Start.
     * Start date for this group
     */
    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * Sets Start.
     * Start date for this group
     *
     * @maps start
     * @factory \RestApiLib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setStart(?\DateTime $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns End.
     * End date for this group
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * Sets End.
     * End date for this group
     *
     * @maps end
     * @factory \RestApiLib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setEnd(?\DateTime $end): void
    {
        $this->end = $end;
    }

    /**
     * Returns Accessor.
     * Optional accessor identifier, null unless grouped by accessor.
     */
    public function getAccessor(): ?string
    {
        if (count($this->accessor) == 0) {
            return null;
        }
        return $this->accessor['value'];
    }

    /**
     * Sets Accessor.
     * Optional accessor identifier, null unless grouped by accessor.
     *
     * @maps accessor
     */
    public function setAccessor(?string $accessor): void
    {
        $this->accessor['value'] = $accessor;
    }

    /**
     * Unsets Accessor.
     * Optional accessor identifier, null unless grouped by accessor.
     */
    public function unsetAccessor(): void
    {
        $this->accessor = [];
    }

    /**
     * Returns Deployment.
     * Optional deployment identifier, null unless grouped by deployment.
     */
    public function getDeployment(): ?string
    {
        if (count($this->deployment) == 0) {
            return null;
        }
        return $this->deployment['value'];
    }

    /**
     * Sets Deployment.
     * Optional deployment identifier, null unless grouped by deployment.
     *
     * @maps deployment
     */
    public function setDeployment(?string $deployment): void
    {
        $this->deployment['value'] = $deployment;
    }

    /**
     * Unsets Deployment.
     * Optional deployment identifier, null unless grouped by deployment.
     */
    public function unsetDeployment(): void
    {
        $this->deployment = [];
    }

    /**
     * Returns Line Item.
     * Optional line item identifier, null unless grouped by line item.
     */
    public function getLineItem(): ?string
    {
        if (count($this->lineItem) == 0) {
            return null;
        }
        return $this->lineItem['value'];
    }

    /**
     * Sets Line Item.
     * Optional line item identifier, null unless grouped by line item.
     *
     * @maps line_item
     */
    public function setLineItem(?string $lineItem): void
    {
        $this->lineItem['value'] = $lineItem;
    }

    /**
     * Unsets Line Item.
     * Optional line item identifier, null unless grouped by line item.
     */
    public function unsetLineItem(): void
    {
        $this->lineItem = [];
    }

    /**
     * Returns Tags.
     * Optional list of tags, null unless grouped by tags.
     *
     * @return string[]|null
     */
    public function getTags(): ?array
    {
        if (count($this->tags) == 0) {
            return null;
        }
        return $this->tags['value'];
    }

    /**
     * Sets Tags.
     * Optional list of tags, null unless grouped by tags.
     *
     * @maps tags
     *
     * @param string[]|null $tags
     */
    public function setTags(?array $tags): void
    {
        $this->tags['value'] = $tags;
    }

    /**
     * Unsets Tags.
     * Optional list of tags, null unless grouped by tags.
     */
    public function unsetTags(): void
    {
        $this->tags = [];
    }

    /**
     * Converts the BillingBreakdownV1ResponseResultsItemsGrouping object to a human-readable string
     * representation.
     *
     * @return string The string representation of the BillingBreakdownV1ResponseResultsItemsGrouping object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BillingBreakdownV1ResponseResultsItemsGrouping',
            [
                'start' => $this->start,
                'end' => $this->end,
                'accessor' => $this->getAccessor(),
                'deployment' => $this->getDeployment(),
                'lineItem' => $this->getLineItem(),
                'tags' => $this->getTags(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['start', 'end', 'accessor', 'deployment', 'line_item', 'tags'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->start)) {
            $json['start']      = DateTimeHelper::toSimpleDate($this->start);
        }
        if (isset($this->end)) {
            $json['end']        = DateTimeHelper::toSimpleDate($this->end);
        }
        if (!empty($this->accessor)) {
            $json['accessor']   = $this->accessor['value'];
        }
        if (!empty($this->deployment)) {
            $json['deployment'] = $this->deployment['value'];
        }
        if (!empty($this->lineItem)) {
            $json['line_item']  = $this->lineItem['value'];
        }
        if (!empty($this->tags)) {
            $json['tags']       = $this->tags['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
