<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class BillingBreakdownV1ResponseResultsItems implements \JsonSerializable
{
    /**
     * @var float
     */
    private $dollars;

    /**
     * @var BillingBreakdownV1ResponseResultsItemsGrouping
     */
    private $grouping;

    /**
     * @param float $dollars
     * @param BillingBreakdownV1ResponseResultsItemsGrouping $grouping
     */
    public function __construct(float $dollars, BillingBreakdownV1ResponseResultsItemsGrouping $grouping)
    {
        $this->dollars = $dollars;
        $this->grouping = $grouping;
    }

    /**
     * Returns Dollars.
     * USD cost of the billing for this grouping
     */
    public function getDollars(): float
    {
        return $this->dollars;
    }

    /**
     * Sets Dollars.
     * USD cost of the billing for this grouping
     *
     * @required
     * @maps dollars
     */
    public function setDollars(float $dollars): void
    {
        $this->dollars = $dollars;
    }

    /**
     * Returns Grouping.
     */
    public function getGrouping(): BillingBreakdownV1ResponseResultsItemsGrouping
    {
        return $this->grouping;
    }

    /**
     * Sets Grouping.
     *
     * @required
     * @maps grouping
     */
    public function setGrouping(BillingBreakdownV1ResponseResultsItemsGrouping $grouping): void
    {
        $this->grouping = $grouping;
    }

    /**
     * Converts the BillingBreakdownV1ResponseResultsItems object to a human-readable string representation.
     *
     * @return string The string representation of the BillingBreakdownV1ResponseResultsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BillingBreakdownV1ResponseResultsItems',
            [
                'dollars' => $this->dollars,
                'grouping' => $this->grouping,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['dollars', 'grouping'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['dollars']  = $this->dollars;
        $json['grouping'] = $this->grouping;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
