<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class CreateProjectDistributionCredentialsV1Response implements \JsonSerializable
{
    /**
     * @var CreateProjectDistributionCredentialsV1ResponseMember
     */
    private $member;

    /**
     * @var CreateProjectDistributionCredentialsV1ResponseDistributionCredentials
     */
    private $distributionCredentials;

    /**
     * @param CreateProjectDistributionCredentialsV1ResponseMember $member
     * @param CreateProjectDistributionCredentialsV1ResponseDistributionCredentials $distributionCredentials
     */
    public function __construct(
        CreateProjectDistributionCredentialsV1ResponseMember $member,
        CreateProjectDistributionCredentialsV1ResponseDistributionCredentials $distributionCredentials
    ) {
        $this->member = $member;
        $this->distributionCredentials = $distributionCredentials;
    }

    /**
     * Returns Member.
     */
    public function getMember(): CreateProjectDistributionCredentialsV1ResponseMember
    {
        return $this->member;
    }

    /**
     * Sets Member.
     *
     * @required
     * @maps member
     */
    public function setMember(CreateProjectDistributionCredentialsV1ResponseMember $member): void
    {
        $this->member = $member;
    }

    /**
     * Returns Distribution Credentials.
     */
    public function getDistributionCredentials(): CreateProjectDistributionCredentialsV1ResponseDistributionCredentials
    {
        return $this->distributionCredentials;
    }

    /**
     * Sets Distribution Credentials.
     *
     * @required
     * @maps distribution_credentials
     */
    public function setDistributionCredentials(
        CreateProjectDistributionCredentialsV1ResponseDistributionCredentials $distributionCredentials
    ): void {
        $this->distributionCredentials = $distributionCredentials;
    }

    /**
     * Converts the CreateProjectDistributionCredentialsV1Response object to a human-readable string
     * representation.
     *
     * @return string The string representation of the CreateProjectDistributionCredentialsV1Response object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateProjectDistributionCredentialsV1Response',
            [
                'member' => $this->member,
                'distributionCredentials' => $this->distributionCredentials,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['member', 'distribution_credentials'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['member']                   = $this->member;
        $json['distribution_credentials'] = $this->distributionCredentials;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
