<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

/**
 * Request body for creating an agent configuration
 */
class CreateAgentConfigurationV1Request implements \JsonSerializable
{
    /**
     * @var string
     */
    private $config;

    /**
     * @var array<string,string>|null
     */
    private $metadata;

    /**
     * @var int|null
     */
    private $apiVersion = 1;

    /**
     * @param string $config
     */
    public function __construct(string $config)
    {
        $this->config = $config;
    }

    /**
     * Returns Config.
     * A valid JSON string representing the agent block of a Settings message
     */
    public function getConfig(): string
    {
        return $this->config;
    }

    /**
     * Sets Config.
     * A valid JSON string representing the agent block of a Settings message
     *
     * @required
     * @maps config
     */
    public function setConfig(string $config): void
    {
        $this->config = $config;
    }

    /**
     * Returns Metadata.
     * A map of arbitrary key-value pairs for labeling or organizing the agent configuration
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     * A map of arbitrary key-value pairs for labeling or organizing the agent configuration
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Api Version.
     * API version. Defaults to 1
     */
    public function getApiVersion(): ?int
    {
        return $this->apiVersion;
    }

    /**
     * Sets Api Version.
     * API version. Defaults to 1
     *
     * @maps api_version
     */
    public function setApiVersion(?int $apiVersion): void
    {
        $this->apiVersion = $apiVersion;
    }

    /**
     * Converts the CreateAgentConfigurationV1Request object to a human-readable string representation.
     *
     * @return string The string representation of the CreateAgentConfigurationV1Request object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateAgentConfigurationV1Request',
            [
                'config' => $this->config,
                'metadata' => $this->metadata,
                'apiVersion' => $this->apiVersion,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['config', 'metadata', 'api_version'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['config']          = $this->config;
        if (isset($this->metadata)) {
            $json['metadata']    = $this->metadata;
        }
        if (isset($this->apiVersion)) {
            $json['api_version'] = $this->apiVersion;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
