<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

/**
 * Request body for creating an agent variable
 */
class CreateAgentVariableV1Request implements \JsonSerializable
{
    /**
     * @var string
     */
    private $key;

    /**
     * @var array
     */
    private $value;

    /**
     * @var int|null
     */
    private $apiVersion = 1;

    /**
     * @param string $key
     * @param array $value
     */
    public function __construct(string $key, array $value)
    {
        $this->key = $key;
        $this->value = $value;
    }

    /**
     * Returns Key.
     * The variable name, following the DG_<VARIABLE_NAME> format
     */
    public function getKey(): string
    {
        return $this->key;
    }

    /**
     * Sets Key.
     * The variable name, following the DG_<VARIABLE_NAME> format
     *
     * @required
     * @maps key
     */
    public function setKey(string $key): void
    {
        $this->key = $key;
    }

    /**
     * Returns Value.
     * The value to substitute. Can be any valid JSON type (string, number, boolean, object, or array)
     */
    public function getValue(): array
    {
        return $this->value;
    }

    /**
     * Sets Value.
     * The value to substitute. Can be any valid JSON type (string, number, boolean, object, or array)
     *
     * @required
     * @maps value
     */
    public function setValue(array $value): void
    {
        $this->value = $value;
    }

    /**
     * Returns Api Version.
     * API version. Defaults to 1
     */
    public function getApiVersion(): ?int
    {
        return $this->apiVersion;
    }

    /**
     * Sets Api Version.
     * API version. Defaults to 1
     *
     * @maps api_version
     */
    public function setApiVersion(?int $apiVersion): void
    {
        $this->apiVersion = $apiVersion;
    }

    /**
     * Converts the CreateAgentVariableV1Request object to a human-readable string representation.
     *
     * @return string The string representation of the CreateAgentVariableV1Request object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateAgentVariableV1Request',
            [
                'key' => $this->key,
                'value' => $this->value,
                'apiVersion' => $this->apiVersion,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['key', 'value', 'api_version'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['key']             = $this->key;
        $json['value']           = $this->value;
        if (isset($this->apiVersion)) {
            $json['api_version'] = $this->apiVersion;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
