<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class ErrorResponseModernError implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $category;

    /**
     * @var string|null
     */
    private $message;

    /**
     * @var string|null
     */
    private $details;

    /**
     * @var string|null
     */
    private $requestId;

    /**
     * Returns Category.
     * The category of the error
     */
    public function getCategory(): ?string
    {
        return $this->category;
    }

    /**
     * Sets Category.
     * The category of the error
     *
     * @maps category
     */
    public function setCategory(?string $category): void
    {
        $this->category = $category;
    }

    /**
     * Returns Message.
     * A message about the error
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * A message about the error
     *
     * @maps message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Details.
     * A description of the error
     */
    public function getDetails(): ?string
    {
        return $this->details;
    }

    /**
     * Sets Details.
     * A description of the error
     *
     * @maps details
     */
    public function setDetails(?string $details): void
    {
        $this->details = $details;
    }

    /**
     * Returns Request Id.
     * The unique identifier of the request
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * The unique identifier of the request
     *
     * @maps request_id
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Converts the ErrorResponseModernError object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorResponseModernError object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorResponseModernError',
            [
                'category' => $this->category,
                'message' => $this->message,
                'details' => $this->details,
                'requestId' => $this->requestId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['category', 'message', 'details', 'request_id'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->category)) {
            $json['category']   = $this->category;
        }
        if (isset($this->message)) {
            $json['message']    = $this->message;
        }
        if (isset($this->details)) {
            $json['details']    = $this->details;
        }
        if (isset($this->requestId)) {
            $json['request_id'] = $this->requestId;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
