<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use RestApiLib\Utils\DateTimeHelper;
use stdClass;

class GetProjectKeyV1ResponseItemMemberApiKey implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $apiKeyId;

    /**
     * @var string|null
     */
    private $comment;

    /**
     * @var string[]|null
     */
    private $scopes;

    /**
     * @var string[]|null
     */
    private $tags;

    /**
     * @var \DateTime|null
     */
    private $expirationDate;

    /**
     * @var \DateTime|null
     */
    private $created;

    /**
     * Returns Api Key Id.
     */
    public function getApiKeyId(): ?string
    {
        return $this->apiKeyId;
    }

    /**
     * Sets Api Key Id.
     *
     * @maps api_key_id
     */
    public function setApiKeyId(?string $apiKeyId): void
    {
        $this->apiKeyId = $apiKeyId;
    }

    /**
     * Returns Comment.
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
     * Sets Comment.
     *
     * @maps comment
     */
    public function setComment(?string $comment): void
    {
        $this->comment = $comment;
    }

    /**
     * Returns Scopes.
     *
     * @return string[]|null
     */
    public function getScopes(): ?array
    {
        return $this->scopes;
    }

    /**
     * Sets Scopes.
     *
     * @maps scopes
     *
     * @param string[]|null $scopes
     */
    public function setScopes(?array $scopes): void
    {
        $this->scopes = $scopes;
    }

    /**
     * Returns Tags.
     *
     * @return string[]|null
     */
    public function getTags(): ?array
    {
        return $this->tags;
    }

    /**
     * Sets Tags.
     *
     * @maps tags
     *
     * @param string[]|null $tags
     */
    public function setTags(?array $tags): void
    {
        $this->tags = $tags;
    }

    /**
     * Returns Expiration Date.
     */
    public function getExpirationDate(): ?\DateTime
    {
        return $this->expirationDate;
    }

    /**
     * Sets Expiration Date.
     *
     * @maps expiration_date
     * @factory \RestApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setExpirationDate(?\DateTime $expirationDate): void
    {
        $this->expirationDate = $expirationDate;
    }

    /**
     * Returns Created.
     */
    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    /**
     * Sets Created.
     *
     * @maps created
     * @factory \RestApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreated(?\DateTime $created): void
    {
        $this->created = $created;
    }

    /**
     * Converts the GetProjectKeyV1ResponseItemMemberApiKey object to a human-readable string
     * representation.
     *
     * @return string The string representation of the GetProjectKeyV1ResponseItemMemberApiKey object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GetProjectKeyV1ResponseItemMemberApiKey',
            [
                'apiKeyId' => $this->apiKeyId,
                'comment' => $this->comment,
                'scopes' => $this->scopes,
                'tags' => $this->tags,
                'expirationDate' => $this->expirationDate,
                'created' => $this->created,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['api_key_id', 'comment', 'scopes', 'tags', 'expiration_date', 'created'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->apiKeyId)) {
            $json['api_key_id']      = $this->apiKeyId;
        }
        if (isset($this->comment)) {
            $json['comment']         = $this->comment;
        }
        if (isset($this->scopes)) {
            $json['scopes']          = $this->scopes;
        }
        if (isset($this->tags)) {
            $json['tags']            = $this->tags;
        }
        if (isset($this->expirationDate)) {
            $json['expiration_date'] = DateTimeHelper::toRfc3339DateTime($this->expirationDate);
        }
        if (isset($this->created)) {
            $json['created']         = DateTimeHelper::toRfc3339DateTime($this->created);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
