<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class GrantV1Response implements \JsonSerializable
{
    /**
     * @var string
     */
    private $accessToken;

    /**
     * @var float|null
     */
    private $expiresIn;

    /**
     * @param string $accessToken
     */
    public function __construct(string $accessToken)
    {
        $this->accessToken = $accessToken;
    }

    /**
     * Returns Access Token.
     * JSON Web Token (JWT)
     */
    public function getAccessToken(): string
    {
        return $this->accessToken;
    }

    /**
     * Sets Access Token.
     * JSON Web Token (JWT)
     *
     * @required
     * @maps access_token
     */
    public function setAccessToken(string $accessToken): void
    {
        $this->accessToken = $accessToken;
    }

    /**
     * Returns Expires In.
     * Time in seconds until the JWT expires
     */
    public function getExpiresIn(): ?float
    {
        return $this->expiresIn;
    }

    /**
     * Sets Expires In.
     * Time in seconds until the JWT expires
     *
     * @maps expires_in
     */
    public function setExpiresIn(?float $expiresIn): void
    {
        $this->expiresIn = $expiresIn;
    }

    /**
     * Converts the GrantV1Response object to a human-readable string representation.
     *
     * @return string The string representation of the GrantV1Response object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GrantV1Response',
            [
                'accessToken' => $this->accessToken,
                'expiresIn' => $this->expiresIn,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['access_token', 'expires_in'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['access_token']   = $this->accessToken;
        if (isset($this->expiresIn)) {
            $json['expires_in'] = $this->expiresIn;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
