<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $confidence;

    /**
     * @var float|null
     */
    private $start;

    /**
     * @var float|null
     */
    private $end;

    /**
     * @var string|null
     */
    private $snippet;

    /**
     * Returns Confidence.
     */
    public function getConfidence(): ?float
    {
        return $this->confidence;
    }

    /**
     * Sets Confidence.
     *
     * @maps confidence
     */
    public function setConfidence(?float $confidence): void
    {
        $this->confidence = $confidence;
    }

    /**
     * Returns Start.
     */
    public function getStart(): ?float
    {
        return $this->start;
    }

    /**
     * Sets Start.
     *
     * @maps start
     */
    public function setStart(?float $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns End.
     */
    public function getEnd(): ?float
    {
        return $this->end;
    }

    /**
     * Sets End.
     *
     * @maps end
     */
    public function setEnd(?float $end): void
    {
        $this->end = $end;
    }

    /**
     * Returns Snippet.
     */
    public function getSnippet(): ?string
    {
        return $this->snippet;
    }

    /**
     * Sets Snippet.
     *
     * @maps snippet
     */
    public function setSnippet(?string $snippet): void
    {
        $this->snippet = $snippet;
    }

    /**
     * Converts the ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems object to a human-readable
     * string representation.
     *
     * @return string The string representation of the ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems',
            [
                'confidence' => $this->confidence,
                'start' => $this->start,
                'end' => $this->end,
                'snippet' => $this->snippet,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['confidence', 'start', 'end', 'snippet'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->confidence)) {
            $json['confidence'] = $this->confidence;
        }
        if (isset($this->start)) {
            $json['start']      = $this->start;
        }
        if (isset($this->end)) {
            $json['end']        = $this->end;
        }
        if (isset($this->snippet)) {
            $json['snippet']    = $this->snippet;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
