<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class ListenV1ResponseResults implements \JsonSerializable
{
    /**
     * @var ListenV1ResponseResultsChannelsItems[]
     */
    private $channels;

    /**
     * @var ListenV1ResponseResultsUtterancesItems[]|null
     */
    private $utterances;

    /**
     * @var ListenV1ResponseResultsSummary|null
     */
    private $summary;

    /**
     * @var SharedTopics|null
     */
    private $topics;

    /**
     * @var SharedIntents|null
     */
    private $intents;

    /**
     * @var SharedSentiments|null
     */
    private $sentiments;

    /**
     * @param ListenV1ResponseResultsChannelsItems[] $channels
     */
    public function __construct(array $channels)
    {
        $this->channels = $channels;
    }

    /**
     * Returns Channels.
     *
     * @return ListenV1ResponseResultsChannelsItems[]
     */
    public function getChannels(): array
    {
        return $this->channels;
    }

    /**
     * Sets Channels.
     *
     * @required
     * @maps channels
     *
     * @param ListenV1ResponseResultsChannelsItems[] $channels
     */
    public function setChannels(array $channels): void
    {
        $this->channels = $channels;
    }

    /**
     * Returns Utterances.
     *
     * @return ListenV1ResponseResultsUtterancesItems[]|null
     */
    public function getUtterances(): ?array
    {
        return $this->utterances;
    }

    /**
     * Sets Utterances.
     *
     * @maps utterances
     *
     * @param ListenV1ResponseResultsUtterancesItems[]|null $utterances
     */
    public function setUtterances(?array $utterances): void
    {
        $this->utterances = $utterances;
    }

    /**
     * Returns Summary.
     */
    public function getSummary(): ?ListenV1ResponseResultsSummary
    {
        return $this->summary;
    }

    /**
     * Sets Summary.
     *
     * @maps summary
     */
    public function setSummary(?ListenV1ResponseResultsSummary $summary): void
    {
        $this->summary = $summary;
    }

    /**
     * Returns Topics.
     * Output whenever `topics=true` is used
     */
    public function getTopics(): ?SharedTopics
    {
        return $this->topics;
    }

    /**
     * Sets Topics.
     * Output whenever `topics=true` is used
     *
     * @maps topics
     */
    public function setTopics(?SharedTopics $topics): void
    {
        $this->topics = $topics;
    }

    /**
     * Returns Intents.
     * Output whenever `intents=true` is used
     */
    public function getIntents(): ?SharedIntents
    {
        return $this->intents;
    }

    /**
     * Sets Intents.
     * Output whenever `intents=true` is used
     *
     * @maps intents
     */
    public function setIntents(?SharedIntents $intents): void
    {
        $this->intents = $intents;
    }

    /**
     * Returns Sentiments.
     * Output whenever `sentiment=true` is used
     */
    public function getSentiments(): ?SharedSentiments
    {
        return $this->sentiments;
    }

    /**
     * Sets Sentiments.
     * Output whenever `sentiment=true` is used
     *
     * @maps sentiments
     */
    public function setSentiments(?SharedSentiments $sentiments): void
    {
        $this->sentiments = $sentiments;
    }

    /**
     * Converts the ListenV1ResponseResults object to a human-readable string representation.
     *
     * @return string The string representation of the ListenV1ResponseResults object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListenV1ResponseResults',
            [
                'channels' => $this->channels,
                'utterances' => $this->utterances,
                'summary' => $this->summary,
                'topics' => $this->topics,
                'intents' => $this->intents,
                'sentiments' => $this->sentiments,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['channels', 'utterances', 'summary', 'topics', 'intents', 'sentiments'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['channels']       = $this->channels;
        if (isset($this->utterances)) {
            $json['utterances'] = $this->utterances;
        }
        if (isset($this->summary)) {
            $json['summary']    = $this->summary;
        }
        if (isset($this->topics)) {
            $json['topics']     = $this->topics;
        }
        if (isset($this->intents)) {
            $json['intents']    = $this->intents;
        }
        if (isset($this->sentiments)) {
            $json['sentiments'] = $this->sentiments;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
