<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class ListAgentVariablesV1Response implements \JsonSerializable
{
    /**
     * @var AgentVariableV1[]|null
     */
    private $variables;

    /**
     * Returns Variables.
     * A list of agent variables for the project
     *
     * @return AgentVariableV1[]|null
     */
    public function getVariables(): ?array
    {
        return $this->variables;
    }

    /**
     * Sets Variables.
     * A list of agent variables for the project
     *
     * @maps variables
     *
     * @param AgentVariableV1[]|null $variables
     */
    public function setVariables(?array $variables): void
    {
        $this->variables = $variables;
    }

    /**
     * Converts the ListAgentVariablesV1Response object to a human-readable string representation.
     *
     * @return string The string representation of the ListAgentVariablesV1Response object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListAgentVariablesV1Response',
            ['variables' => $this->variables, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['variables'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->variables)) {
            $json['variables'] = $this->variables;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
