<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class ListenV1ResponseResultsChannelsItemsSearchItems implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $query;

    /**
     * @var ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems[]|null
     */
    private $hits;

    /**
     * Returns Query.
     */
    public function getQuery(): ?string
    {
        return $this->query;
    }

    /**
     * Sets Query.
     *
     * @maps query
     */
    public function setQuery(?string $query): void
    {
        $this->query = $query;
    }

    /**
     * Returns Hits.
     *
     * @return ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems[]|null
     */
    public function getHits(): ?array
    {
        return $this->hits;
    }

    /**
     * Sets Hits.
     *
     * @maps hits
     *
     * @param ListenV1ResponseResultsChannelsItemsSearchItemsHitsItems[]|null $hits
     */
    public function setHits(?array $hits): void
    {
        $this->hits = $hits;
    }

    /**
     * Converts the ListenV1ResponseResultsChannelsItemsSearchItems object to a human-readable string
     * representation.
     *
     * @return string The string representation of the ListenV1ResponseResultsChannelsItemsSearchItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListenV1ResponseResultsChannelsItemsSearchItems',
            ['query' => $this->query, 'hits' => $this->hits, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['query', 'hits'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->query)) {
            $json['query'] = $this->query;
        }
        if (isset($this->hits)) {
            $json['hits']  = $this->hits;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
