<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class ListModelsV1ResponseSttModels implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $canonicalName;

    /**
     * @var string|null
     */
    private $architecture;

    /**
     * @var string[]|null
     */
    private $languages;

    /**
     * @var string|null
     */
    private $version;

    /**
     * @var string|null
     */
    private $uuid;

    /**
     * @var bool|null
     */
    private $batch;

    /**
     * @var bool|null
     */
    private $streaming;

    /**
     * @var bool|null
     */
    private $formattedOutput;

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Canonical Name.
     */
    public function getCanonicalName(): ?string
    {
        return $this->canonicalName;
    }

    /**
     * Sets Canonical Name.
     *
     * @maps canonical_name
     */
    public function setCanonicalName(?string $canonicalName): void
    {
        $this->canonicalName = $canonicalName;
    }

    /**
     * Returns Architecture.
     */
    public function getArchitecture(): ?string
    {
        return $this->architecture;
    }

    /**
     * Sets Architecture.
     *
     * @maps architecture
     */
    public function setArchitecture(?string $architecture): void
    {
        $this->architecture = $architecture;
    }

    /**
     * Returns Languages.
     *
     * @return string[]|null
     */
    public function getLanguages(): ?array
    {
        return $this->languages;
    }

    /**
     * Sets Languages.
     *
     * @maps languages
     *
     * @param string[]|null $languages
     */
    public function setLanguages(?array $languages): void
    {
        $this->languages = $languages;
    }

    /**
     * Returns Version.
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * Sets Version.
     *
     * @maps version
     */
    public function setVersion(?string $version): void
    {
        $this->version = $version;
    }

    /**
     * Returns Uuid.
     */
    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    /**
     * Sets Uuid.
     *
     * @maps uuid
     */
    public function setUuid(?string $uuid): void
    {
        $this->uuid = $uuid;
    }

    /**
     * Returns Batch.
     */
    public function getBatch(): ?bool
    {
        return $this->batch;
    }

    /**
     * Sets Batch.
     *
     * @maps batch
     */
    public function setBatch(?bool $batch): void
    {
        $this->batch = $batch;
    }

    /**
     * Returns Streaming.
     */
    public function getStreaming(): ?bool
    {
        return $this->streaming;
    }

    /**
     * Sets Streaming.
     *
     * @maps streaming
     */
    public function setStreaming(?bool $streaming): void
    {
        $this->streaming = $streaming;
    }

    /**
     * Returns Formatted Output.
     */
    public function getFormattedOutput(): ?bool
    {
        return $this->formattedOutput;
    }

    /**
     * Sets Formatted Output.
     *
     * @maps formatted_output
     */
    public function setFormattedOutput(?bool $formattedOutput): void
    {
        $this->formattedOutput = $formattedOutput;
    }

    /**
     * Converts the ListModelsV1ResponseSttModels object to a human-readable string representation.
     *
     * @return string The string representation of the ListModelsV1ResponseSttModels object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListModelsV1ResponseSttModels',
            [
                'name' => $this->name,
                'canonicalName' => $this->canonicalName,
                'architecture' => $this->architecture,
                'languages' => $this->languages,
                'version' => $this->version,
                'uuid' => $this->uuid,
                'batch' => $this->batch,
                'streaming' => $this->streaming,
                'formattedOutput' => $this->formattedOutput,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'name',
        'canonical_name',
        'architecture',
        'languages',
        'version',
        'uuid',
        'batch',
        'streaming',
        'formatted_output'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']             = $this->name;
        }
        if (isset($this->canonicalName)) {
            $json['canonical_name']   = $this->canonicalName;
        }
        if (isset($this->architecture)) {
            $json['architecture']     = $this->architecture;
        }
        if (isset($this->languages)) {
            $json['languages']        = $this->languages;
        }
        if (isset($this->version)) {
            $json['version']          = $this->version;
        }
        if (isset($this->uuid)) {
            $json['uuid']             = $this->uuid;
        }
        if (isset($this->batch)) {
            $json['batch']            = $this->batch;
        }
        if (isset($this->streaming)) {
            $json['streaming']        = $this->streaming;
        }
        if (isset($this->formattedOutput)) {
            $json['formatted_output'] = $this->formattedOutput;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
