<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class ListProjectsV1ResponseProjectsItems implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $projectId;

    /**
     * @var string|null
     */
    private $name;

    /**
     * Returns Project Id.
     * The unique identifier of the project
     */
    public function getProjectId(): ?string
    {
        return $this->projectId;
    }

    /**
     * Sets Project Id.
     * The unique identifier of the project
     *
     * @maps project_id
     */
    public function setProjectId(?string $projectId): void
    {
        $this->projectId = $projectId;
    }

    /**
     * Returns Name.
     * The name of the project
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the project
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Converts the ListProjectsV1ResponseProjectsItems object to a human-readable string representation.
     *
     * @return string The string representation of the ListProjectsV1ResponseProjectsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListProjectsV1ResponseProjectsItems',
            [
                'projectId' => $this->projectId,
                'name' => $this->name,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['project_id', 'name'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->projectId)) {
            $json['project_id'] = $this->projectId;
        }
        if (isset($this->name)) {
            $json['name']       = $this->name;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
