<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class ListProjectKeysV1ResponseApiKeysItems implements \JsonSerializable
{
    /**
     * @var ListProjectKeysV1ResponseApiKeysItemsMember|null
     */
    private $member;

    /**
     * @var ListProjectKeysV1ResponseApiKeysItemsApiKey|null
     */
    private $apiKey;

    /**
     * Returns Member.
     */
    public function getMember(): ?ListProjectKeysV1ResponseApiKeysItemsMember
    {
        return $this->member;
    }

    /**
     * Sets Member.
     *
     * @maps member
     */
    public function setMember(?ListProjectKeysV1ResponseApiKeysItemsMember $member): void
    {
        $this->member = $member;
    }

    /**
     * Returns Api Key.
     */
    public function getApiKey(): ?ListProjectKeysV1ResponseApiKeysItemsApiKey
    {
        return $this->apiKey;
    }

    /**
     * Sets Api Key.
     *
     * @maps api_key
     */
    public function setApiKey(?ListProjectKeysV1ResponseApiKeysItemsApiKey $apiKey): void
    {
        $this->apiKey = $apiKey;
    }

    /**
     * Converts the ListProjectKeysV1ResponseApiKeysItems object to a human-readable string representation.
     *
     * @return string The string representation of the ListProjectKeysV1ResponseApiKeysItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListProjectKeysV1ResponseApiKeysItems',
            [
                'member' => $this->member,
                'apiKey' => $this->apiKey,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['member', 'api_key'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->member)) {
            $json['member']  = $this->member;
        }
        if (isset($this->apiKey)) {
            $json['api_key'] = $this->apiKey;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
