<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class ListProjectKeysV1ResponseApiKeysItemsMember implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $memberId;

    /**
     * @var string|null
     */
    private $email;

    /**
     * Returns Member Id.
     */
    public function getMemberId(): ?string
    {
        return $this->memberId;
    }

    /**
     * Sets Member Id.
     *
     * @maps member_id
     */
    public function setMemberId(?string $memberId): void
    {
        $this->memberId = $memberId;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @maps email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Converts the ListProjectKeysV1ResponseApiKeysItemsMember object to a human-readable string
     * representation.
     *
     * @return string The string representation of the ListProjectKeysV1ResponseApiKeysItemsMember object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListProjectKeysV1ResponseApiKeysItemsMember',
            [
                'memberId' => $this->memberId,
                'email' => $this->email,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['member_id', 'email'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->memberId)) {
            $json['member_id'] = $this->memberId;
        }
        if (isset($this->email)) {
            $json['email']     = $this->email;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
