<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $transcript;

    /**
     * @var ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems[]|null
     */
    private $paragraphs;

    /**
     * Returns Transcript.
     */
    public function getTranscript(): ?string
    {
        return $this->transcript;
    }

    /**
     * Sets Transcript.
     *
     * @maps transcript
     */
    public function setTranscript(?string $transcript): void
    {
        $this->transcript = $transcript;
    }

    /**
     * Returns Paragraphs.
     *
     * @return ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems[]|null
     */
    public function getParagraphs(): ?array
    {
        return $this->paragraphs;
    }

    /**
     * Sets Paragraphs.
     *
     * @maps paragraphs
     *
     * @param ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphsParagraphsItems[]|null $paragraphs
     */
    public function setParagraphs(?array $paragraphs): void
    {
        $this->paragraphs = $paragraphs;
    }

    /**
     * Converts the ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs object to a human-
     * readable string representation.
     *
     * @return string The string representation of the ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListenV1ResponseResultsChannelsItemsAlternativesItemsParagraphs',
            [
                'transcript' => $this->transcript,
                'paragraphs' => $this->paragraphs,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['transcript', 'paragraphs'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->transcript)) {
            $json['transcript'] = $this->transcript;
        }
        if (isset($this->paragraphs)) {
            $json['paragraphs'] = $this->paragraphs;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
