<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class ListModelsV1Response implements \JsonSerializable
{
    /**
     * @var ListModelsV1ResponseSttModels[]|null
     */
    private $stt;

    /**
     * @var ListModelsV1ResponseTtsModels[]|null
     */
    private $tts;

    /**
     * Returns Stt.
     *
     * @return ListModelsV1ResponseSttModels[]|null
     */
    public function getStt(): ?array
    {
        return $this->stt;
    }

    /**
     * Sets Stt.
     *
     * @maps stt
     *
     * @param ListModelsV1ResponseSttModels[]|null $stt
     */
    public function setStt(?array $stt): void
    {
        $this->stt = $stt;
    }

    /**
     * Returns Tts.
     *
     * @return ListModelsV1ResponseTtsModels[]|null
     */
    public function getTts(): ?array
    {
        return $this->tts;
    }

    /**
     * Sets Tts.
     *
     * @maps tts
     *
     * @param ListModelsV1ResponseTtsModels[]|null $tts
     */
    public function setTts(?array $tts): void
    {
        $this->tts = $tts;
    }

    /**
     * Converts the ListModelsV1Response object to a human-readable string representation.
     *
     * @return string The string representation of the ListModelsV1Response object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListModelsV1Response',
            ['stt' => $this->stt, 'tts' => $this->tts, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['stt', 'tts'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->stt)) {
            $json['stt'] = $this->stt;
        }
        if (isset($this->tts)) {
            $json['tts'] = $this->tts;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
