<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class ListenV1ResponseResultsUtterancesItemsWordsItems implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $word;

    /**
     * @var float|null
     */
    private $start;

    /**
     * @var float|null
     */
    private $end;

    /**
     * @var float|null
     */
    private $confidence;

    /**
     * @var int|null
     */
    private $speaker;

    /**
     * @var float|null
     */
    private $speakerConfidence;

    /**
     * @var string|null
     */
    private $punctuatedWord;

    /**
     * Returns Word.
     */
    public function getWord(): ?string
    {
        return $this->word;
    }

    /**
     * Sets Word.
     *
     * @maps word
     */
    public function setWord(?string $word): void
    {
        $this->word = $word;
    }

    /**
     * Returns Start.
     */
    public function getStart(): ?float
    {
        return $this->start;
    }

    /**
     * Sets Start.
     *
     * @maps start
     */
    public function setStart(?float $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns End.
     */
    public function getEnd(): ?float
    {
        return $this->end;
    }

    /**
     * Sets End.
     *
     * @maps end
     */
    public function setEnd(?float $end): void
    {
        $this->end = $end;
    }

    /**
     * Returns Confidence.
     */
    public function getConfidence(): ?float
    {
        return $this->confidence;
    }

    /**
     * Sets Confidence.
     *
     * @maps confidence
     */
    public function setConfidence(?float $confidence): void
    {
        $this->confidence = $confidence;
    }

    /**
     * Returns Speaker.
     */
    public function getSpeaker(): ?int
    {
        return $this->speaker;
    }

    /**
     * Sets Speaker.
     *
     * @maps speaker
     */
    public function setSpeaker(?int $speaker): void
    {
        $this->speaker = $speaker;
    }

    /**
     * Returns Speaker Confidence.
     */
    public function getSpeakerConfidence(): ?float
    {
        return $this->speakerConfidence;
    }

    /**
     * Sets Speaker Confidence.
     *
     * @maps speaker_confidence
     */
    public function setSpeakerConfidence(?float $speakerConfidence): void
    {
        $this->speakerConfidence = $speakerConfidence;
    }

    /**
     * Returns Punctuated Word.
     */
    public function getPunctuatedWord(): ?string
    {
        return $this->punctuatedWord;
    }

    /**
     * Sets Punctuated Word.
     *
     * @maps punctuated_word
     */
    public function setPunctuatedWord(?string $punctuatedWord): void
    {
        $this->punctuatedWord = $punctuatedWord;
    }

    /**
     * Converts the ListenV1ResponseResultsUtterancesItemsWordsItems object to a human-readable string
     * representation.
     *
     * @return string The string representation of the ListenV1ResponseResultsUtterancesItemsWordsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ListenV1ResponseResultsUtterancesItemsWordsItems',
            [
                'word' => $this->word,
                'start' => $this->start,
                'end' => $this->end,
                'confidence' => $this->confidence,
                'speaker' => $this->speaker,
                'speakerConfidence' => $this->speakerConfidence,
                'punctuatedWord' => $this->punctuatedWord,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'word',
        'start',
        'end',
        'confidence',
        'speaker',
        'speaker_confidence',
        'punctuated_word'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->word)) {
            $json['word']               = $this->word;
        }
        if (isset($this->start)) {
            $json['start']              = $this->start;
        }
        if (isset($this->end)) {
            $json['end']                = $this->end;
        }
        if (isset($this->confidence)) {
            $json['confidence']         = $this->confidence;
        }
        if (isset($this->speaker)) {
            $json['speaker']            = $this->speaker;
        }
        if (isset($this->speakerConfidence)) {
            $json['speaker_confidence'] = $this->speakerConfidence;
        }
        if (isset($this->punctuatedWord)) {
            $json['punctuated_word']    = $this->punctuatedWord;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
