<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use DeepgramLib\Utils\DateTimeHelper;
use stdClass;

/**
 * A single request
 */
class ProjectRequestResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $requestId;

    /**
     * @var string|null
     */
    private $projectUuid;

    /**
     * @var \DateTime|null
     */
    private $created;

    /**
     * @var string|null
     */
    private $path;

    /**
     * @var string|null
     */
    private $apiKeyId;

    /**
     * @var array|null
     */
    private $response;

    /**
     * @var float|null
     */
    private $code;

    /**
     * @var string|null
     */
    private $deployment;

    /**
     * @var string|null
     */
    private $callback;

    /**
     * Returns Request Id.
     * The unique identifier of the request
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * The unique identifier of the request
     *
     * @maps request_id
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Project Uuid.
     * The unique identifier of the project
     */
    public function getProjectUuid(): ?string
    {
        return $this->projectUuid;
    }

    /**
     * Sets Project Uuid.
     * The unique identifier of the project
     *
     * @maps project_uuid
     */
    public function setProjectUuid(?string $projectUuid): void
    {
        $this->projectUuid = $projectUuid;
    }

    /**
     * Returns Created.
     * The date and time the request was created
     */
    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * The date and time the request was created
     *
     * @maps created
     * @factory \DeepgramLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreated(?\DateTime $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Path.
     * The API path of the request
     */
    public function getPath(): ?string
    {
        return $this->path;
    }

    /**
     * Sets Path.
     * The API path of the request
     *
     * @maps path
     */
    public function setPath(?string $path): void
    {
        $this->path = $path;
    }

    /**
     * Returns Api Key Id.
     * The unique identifier of the API key
     */
    public function getApiKeyId(): ?string
    {
        return $this->apiKeyId;
    }

    /**
     * Sets Api Key Id.
     * The unique identifier of the API key
     *
     * @maps api_key_id
     */
    public function setApiKeyId(?string $apiKeyId): void
    {
        $this->apiKeyId = $apiKeyId;
    }

    /**
     * Returns Response.
     * The response of the request
     */
    public function getResponse(): ?array
    {
        return $this->response;
    }

    /**
     * Sets Response.
     * The response of the request
     *
     * @maps response
     */
    public function setResponse(?array $response): void
    {
        $this->response = $response;
    }

    /**
     * Returns Code.
     * The response code of the request
     */
    public function getCode(): ?float
    {
        return $this->code;
    }

    /**
     * Sets Code.
     * The response code of the request
     *
     * @maps code
     */
    public function setCode(?float $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Deployment.
     * The deployment type
     */
    public function getDeployment(): ?string
    {
        return $this->deployment;
    }

    /**
     * Sets Deployment.
     * The deployment type
     *
     * @maps deployment
     */
    public function setDeployment(?string $deployment): void
    {
        $this->deployment = $deployment;
    }

    /**
     * Returns Callback.
     * The callback URL for the request
     */
    public function getCallback(): ?string
    {
        return $this->callback;
    }

    /**
     * Sets Callback.
     * The callback URL for the request
     *
     * @maps callback
     */
    public function setCallback(?string $callback): void
    {
        $this->callback = $callback;
    }

    /**
     * Converts the ProjectRequestResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ProjectRequestResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ProjectRequestResponse',
            [
                'requestId' => $this->requestId,
                'projectUuid' => $this->projectUuid,
                'created' => $this->created,
                'path' => $this->path,
                'apiKeyId' => $this->apiKeyId,
                'response' => $this->response,
                'code' => $this->code,
                'deployment' => $this->deployment,
                'callback' => $this->callback,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'request_id',
        'project_uuid',
        'created',
        'path',
        'api_key_id',
        'response',
        'code',
        'deployment',
        'callback'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->requestId)) {
            $json['request_id']   = $this->requestId;
        }
        if (isset($this->projectUuid)) {
            $json['project_uuid'] = $this->projectUuid;
        }
        if (isset($this->created)) {
            $json['created']      = DateTimeHelper::toRfc3339DateTime($this->created);
        }
        if (isset($this->path)) {
            $json['path']         = $this->path;
        }
        if (isset($this->apiKeyId)) {
            $json['api_key_id']   = $this->apiKeyId;
        }
        if (isset($this->response)) {
            $json['response']     = $this->response;
        }
        if (isset($this->code)) {
            $json['code']         = $this->code;
        }
        if (isset($this->deployment)) {
            $json['deployment']   = $this->deployment;
        }
        if (isset($this->callback)) {
            $json['callback']     = $this->callback;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
