<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class SharedSentimentsSegmentsItems implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $text;

    /**
     * @var float|null
     */
    private $startWord;

    /**
     * @var float|null
     */
    private $endWord;

    /**
     * @var string|null
     */
    private $sentiment;

    /**
     * @var float|null
     */
    private $sentimentScore;

    /**
     * Returns Text.
     */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     *
     * @maps text
     */
    public function setText(?string $text): void
    {
        $this->text = $text;
    }

    /**
     * Returns Start Word.
     */
    public function getStartWord(): ?float
    {
        return $this->startWord;
    }

    /**
     * Sets Start Word.
     *
     * @maps start_word
     */
    public function setStartWord(?float $startWord): void
    {
        $this->startWord = $startWord;
    }

    /**
     * Returns End Word.
     */
    public function getEndWord(): ?float
    {
        return $this->endWord;
    }

    /**
     * Sets End Word.
     *
     * @maps end_word
     */
    public function setEndWord(?float $endWord): void
    {
        $this->endWord = $endWord;
    }

    /**
     * Returns Sentiment.
     */
    public function getSentiment(): ?string
    {
        return $this->sentiment;
    }

    /**
     * Sets Sentiment.
     *
     * @maps sentiment
     */
    public function setSentiment(?string $sentiment): void
    {
        $this->sentiment = $sentiment;
    }

    /**
     * Returns Sentiment Score.
     */
    public function getSentimentScore(): ?float
    {
        return $this->sentimentScore;
    }

    /**
     * Sets Sentiment Score.
     *
     * @maps sentiment_score
     */
    public function setSentimentScore(?float $sentimentScore): void
    {
        $this->sentimentScore = $sentimentScore;
    }

    /**
     * Converts the SharedSentimentsSegmentsItems object to a human-readable string representation.
     *
     * @return string The string representation of the SharedSentimentsSegmentsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SharedSentimentsSegmentsItems',
            [
                'text' => $this->text,
                'startWord' => $this->startWord,
                'endWord' => $this->endWord,
                'sentiment' => $this->sentiment,
                'sentimentScore' => $this->sentimentScore,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['text', 'start_word', 'end_word', 'sentiment', 'sentiment_score'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->text)) {
            $json['text']            = $this->text;
        }
        if (isset($this->startWord)) {
            $json['start_word']      = $this->startWord;
        }
        if (isset($this->endWord)) {
            $json['end_word']        = $this->endWord;
        }
        if (isset($this->sentiment)) {
            $json['sentiment']       = $this->sentiment;
        }
        if (isset($this->sentimentScore)) {
            $json['sentiment_score'] = $this->sentimentScore;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
