<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

class SharedTopicsResultsTopicsSegmentsItemsTopicsItems implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $topic;

    /**
     * @var float|null
     */
    private $confidenceScore;

    /**
     * Returns Topic.
     */
    public function getTopic(): ?string
    {
        return $this->topic;
    }

    /**
     * Sets Topic.
     *
     * @maps topic
     */
    public function setTopic(?string $topic): void
    {
        $this->topic = $topic;
    }

    /**
     * Returns Confidence Score.
     */
    public function getConfidenceScore(): ?float
    {
        return $this->confidenceScore;
    }

    /**
     * Sets Confidence Score.
     *
     * @maps confidence_score
     */
    public function setConfidenceScore(?float $confidenceScore): void
    {
        $this->confidenceScore = $confidenceScore;
    }

    /**
     * Converts the SharedTopicsResultsTopicsSegmentsItemsTopicsItems object to a human-readable string
     * representation.
     *
     * @return string The string representation of the SharedTopicsResultsTopicsSegmentsItemsTopicsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SharedTopicsResultsTopicsSegmentsItemsTopicsItems',
            [
                'topic' => $this->topic,
                'confidenceScore' => $this->confidenceScore,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['topic', 'confidence_score'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->topic)) {
            $json['topic']            = $this->topic;
        }
        if (isset($this->confidenceScore)) {
            $json['confidence_score'] = $this->confidenceScore;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
