<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use stdClass;

/**
 * Output whenever `sentiment=true` is used
 */
class SharedSentiments implements \JsonSerializable
{
    /**
     * @var SharedSentimentsSegmentsItems[]|null
     */
    private $segments;

    /**
     * @var SharedSentimentsAverage|null
     */
    private $average;

    /**
     * Returns Segments.
     *
     * @return SharedSentimentsSegmentsItems[]|null
     */
    public function getSegments(): ?array
    {
        return $this->segments;
    }

    /**
     * Sets Segments.
     *
     * @maps segments
     *
     * @param SharedSentimentsSegmentsItems[]|null $segments
     */
    public function setSegments(?array $segments): void
    {
        $this->segments = $segments;
    }

    /**
     * Returns Average.
     */
    public function getAverage(): ?SharedSentimentsAverage
    {
        return $this->average;
    }

    /**
     * Sets Average.
     *
     * @maps average
     */
    public function setAverage(?SharedSentimentsAverage $average): void
    {
        $this->average = $average;
    }

    /**
     * Converts the SharedSentiments object to a human-readable string representation.
     *
     * @return string The string representation of the SharedSentiments object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SharedSentiments',
            [
                'segments' => $this->segments,
                'average' => $this->average,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['segments', 'average'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->segments)) {
            $json['segments'] = $this->segments;
        }
        if (isset($this->average)) {
            $json['average']  = $this->average;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
