<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

/**
 * Request body for Flux TTS batch (REST) text-to-speech conversion. The full block of text is
 * synthesized in a single request and returned as one audio response.
 */
class SpeakV2Request implements \JsonSerializable
{
    /**
     * @var string
     */
    private $text;

    /**
     * @param string $text
     */
    public function __construct(string $text)
    {
        $this->text = $text;
    }

    /**
     * Returns Text.
     * The text content to be converted to speech. The server normalizes and preprocesses the text (e.g.
     * stripping inline controls) before synthesis.
     */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     * The text content to be converted to speech. The server normalizes and preprocesses the text (e.g.
     * stripping inline controls) before synthesis.
     *
     * @required
     * @maps text
     */
    public function setText(string $text): void
    {
        $this->text = $text;
    }

    /**
     * Converts the SpeakV2Request object to a human-readable string representation.
     *
     * @return string The string representation of the SpeakV2Request object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SpeakV2Request',
            ['text' => $this->text, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['text'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['text'] = $this->text;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
