<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class UsageBreakdownV1ResponseResultsItems implements \JsonSerializable
{
    /**
     * @var float
     */
    private $hours;

    /**
     * @var float
     */
    private $totalHours;

    /**
     * @var float
     */
    private $agentHours;

    /**
     * @var float
     */
    private $tokensIn;

    /**
     * @var float
     */
    private $tokensOut;

    /**
     * @var float
     */
    private $ttsCharacters;

    /**
     * @var float
     */
    private $requests;

    /**
     * @var UsageBreakdownV1ResponseResultsItemsGrouping
     */
    private $grouping;

    /**
     * @param float $hours
     * @param float $totalHours
     * @param float $agentHours
     * @param float $tokensIn
     * @param float $tokensOut
     * @param float $ttsCharacters
     * @param float $requests
     * @param UsageBreakdownV1ResponseResultsItemsGrouping $grouping
     */
    public function __construct(
        float $hours,
        float $totalHours,
        float $agentHours,
        float $tokensIn,
        float $tokensOut,
        float $ttsCharacters,
        float $requests,
        UsageBreakdownV1ResponseResultsItemsGrouping $grouping
    ) {
        $this->hours = $hours;
        $this->totalHours = $totalHours;
        $this->agentHours = $agentHours;
        $this->tokensIn = $tokensIn;
        $this->tokensOut = $tokensOut;
        $this->ttsCharacters = $ttsCharacters;
        $this->requests = $requests;
        $this->grouping = $grouping;
    }

    /**
     * Returns Hours.
     * Audio hours processed
     */
    public function getHours(): float
    {
        return $this->hours;
    }

    /**
     * Sets Hours.
     * Audio hours processed
     *
     * @required
     * @maps hours
     */
    public function setHours(float $hours): void
    {
        $this->hours = $hours;
    }

    /**
     * Returns Total Hours.
     * Total hours including all processing
     */
    public function getTotalHours(): float
    {
        return $this->totalHours;
    }

    /**
     * Sets Total Hours.
     * Total hours including all processing
     *
     * @required
     * @maps total_hours
     */
    public function setTotalHours(float $totalHours): void
    {
        $this->totalHours = $totalHours;
    }

    /**
     * Returns Agent Hours.
     * Agent hours used
     */
    public function getAgentHours(): float
    {
        return $this->agentHours;
    }

    /**
     * Sets Agent Hours.
     * Agent hours used
     *
     * @required
     * @maps agent_hours
     */
    public function setAgentHours(float $agentHours): void
    {
        $this->agentHours = $agentHours;
    }

    /**
     * Returns Tokens In.
     * Number of input tokens
     */
    public function getTokensIn(): float
    {
        return $this->tokensIn;
    }

    /**
     * Sets Tokens In.
     * Number of input tokens
     *
     * @required
     * @maps tokens_in
     */
    public function setTokensIn(float $tokensIn): void
    {
        $this->tokensIn = $tokensIn;
    }

    /**
     * Returns Tokens Out.
     * Number of output tokens
     */
    public function getTokensOut(): float
    {
        return $this->tokensOut;
    }

    /**
     * Sets Tokens Out.
     * Number of output tokens
     *
     * @required
     * @maps tokens_out
     */
    public function setTokensOut(float $tokensOut): void
    {
        $this->tokensOut = $tokensOut;
    }

    /**
     * Returns Tts Characters.
     * Number of text-to-speech characters processed
     */
    public function getTtsCharacters(): float
    {
        return $this->ttsCharacters;
    }

    /**
     * Sets Tts Characters.
     * Number of text-to-speech characters processed
     *
     * @required
     * @maps tts_characters
     */
    public function setTtsCharacters(float $ttsCharacters): void
    {
        $this->ttsCharacters = $ttsCharacters;
    }

    /**
     * Returns Requests.
     * Number of requests
     */
    public function getRequests(): float
    {
        return $this->requests;
    }

    /**
     * Sets Requests.
     * Number of requests
     *
     * @required
     * @maps requests
     */
    public function setRequests(float $requests): void
    {
        $this->requests = $requests;
    }

    /**
     * Returns Grouping.
     */
    public function getGrouping(): UsageBreakdownV1ResponseResultsItemsGrouping
    {
        return $this->grouping;
    }

    /**
     * Sets Grouping.
     *
     * @required
     * @maps grouping
     */
    public function setGrouping(UsageBreakdownV1ResponseResultsItemsGrouping $grouping): void
    {
        $this->grouping = $grouping;
    }

    /**
     * Converts the UsageBreakdownV1ResponseResultsItems object to a human-readable string representation.
     *
     * @return string The string representation of the UsageBreakdownV1ResponseResultsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UsageBreakdownV1ResponseResultsItems',
            [
                'hours' => $this->hours,
                'totalHours' => $this->totalHours,
                'agentHours' => $this->agentHours,
                'tokensIn' => $this->tokensIn,
                'tokensOut' => $this->tokensOut,
                'ttsCharacters' => $this->ttsCharacters,
                'requests' => $this->requests,
                'grouping' => $this->grouping,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'hours',
        'total_hours',
        'agent_hours',
        'tokens_in',
        'tokens_out',
        'tts_characters',
        'requests',
        'grouping'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['hours']          = $this->hours;
        $json['total_hours']    = $this->totalHours;
        $json['agent_hours']    = $this->agentHours;
        $json['tokens_in']      = $this->tokensIn;
        $json['tokens_out']     = $this->tokensOut;
        $json['tts_characters'] = $this->ttsCharacters;
        $json['requests']       = $this->requests;
        $json['grouping']       = $this->grouping;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
