<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use DeepgramLib\ApiHelper;
use DeepgramLib\Utils\DateTimeHelper;
use stdClass;

class UsageBreakdownV1ResponseResultsItemsGrouping implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $start;

    /**
     * @var \DateTime|null
     */
    private $end;

    /**
     * @var array
     */
    private $accessor = [];

    /**
     * @var array
     */
    private $endpoint = [];

    /**
     * @var array
     */
    private $featureSet = [];

    /**
     * @var string[]|null
     */
    private $models;

    /**
     * @var array
     */
    private $method = [];

    /**
     * @var array
     */
    private $tags = [];

    /**
     * @var array
     */
    private $deployment = [];

    /**
     * Returns Start.
     * Start date for this group
     */
    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * Sets Start.
     * Start date for this group
     *
     * @maps start
     * @factory \DeepgramLib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setStart(?\DateTime $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns End.
     * End date for this group
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * Sets End.
     * End date for this group
     *
     * @maps end
     * @factory \DeepgramLib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setEnd(?\DateTime $end): void
    {
        $this->end = $end;
    }

    /**
     * Returns Accessor.
     * Optional accessor identifier
     */
    public function getAccessor(): ?string
    {
        if (count($this->accessor) == 0) {
            return null;
        }
        return $this->accessor['value'];
    }

    /**
     * Sets Accessor.
     * Optional accessor identifier
     *
     * @maps accessor
     */
    public function setAccessor(?string $accessor): void
    {
        $this->accessor['value'] = $accessor;
    }

    /**
     * Unsets Accessor.
     * Optional accessor identifier
     */
    public function unsetAccessor(): void
    {
        $this->accessor = [];
    }

    /**
     * Returns Endpoint.
     * Optional endpoint identifier
     */
    public function getEndpoint(): ?string
    {
        if (count($this->endpoint) == 0) {
            return null;
        }
        return $this->endpoint['value'];
    }

    /**
     * Sets Endpoint.
     * Optional endpoint identifier
     *
     * @maps endpoint
     */
    public function setEndpoint(?string $endpoint): void
    {
        $this->endpoint['value'] = $endpoint;
    }

    /**
     * Unsets Endpoint.
     * Optional endpoint identifier
     */
    public function unsetEndpoint(): void
    {
        $this->endpoint = [];
    }

    /**
     * Returns Feature Set.
     * Optional feature set identifier
     */
    public function getFeatureSet(): ?string
    {
        if (count($this->featureSet) == 0) {
            return null;
        }
        return $this->featureSet['value'];
    }

    /**
     * Sets Feature Set.
     * Optional feature set identifier
     *
     * @maps feature_set
     */
    public function setFeatureSet(?string $featureSet): void
    {
        $this->featureSet['value'] = $featureSet;
    }

    /**
     * Unsets Feature Set.
     * Optional feature set identifier
     */
    public function unsetFeatureSet(): void
    {
        $this->featureSet = [];
    }

    /**
     * Returns Models.
     *
     * @return string[]|null
     */
    public function getModels(): ?array
    {
        return $this->models;
    }

    /**
     * Sets Models.
     *
     * @maps models
     *
     * @param string[]|null $models
     */
    public function setModels(?array $models): void
    {
        $this->models = $models;
    }

    /**
     * Returns Method.
     * Optional method identifier
     */
    public function getMethod(): ?string
    {
        if (count($this->method) == 0) {
            return null;
        }
        return $this->method['value'];
    }

    /**
     * Sets Method.
     * Optional method identifier
     *
     * @maps method
     */
    public function setMethod(?string $method): void
    {
        $this->method['value'] = $method;
    }

    /**
     * Unsets Method.
     * Optional method identifier
     */
    public function unsetMethod(): void
    {
        $this->method = [];
    }

    /**
     * Returns Tags.
     * Optional list of tags, null unless grouped by tags.
     *
     * @return string[]|null
     */
    public function getTags(): ?array
    {
        if (count($this->tags) == 0) {
            return null;
        }
        return $this->tags['value'];
    }

    /**
     * Sets Tags.
     * Optional list of tags, null unless grouped by tags.
     *
     * @maps tags
     *
     * @param string[]|null $tags
     */
    public function setTags(?array $tags): void
    {
        $this->tags['value'] = $tags;
    }

    /**
     * Unsets Tags.
     * Optional list of tags, null unless grouped by tags.
     */
    public function unsetTags(): void
    {
        $this->tags = [];
    }

    /**
     * Returns Deployment.
     * Optional deployment identifier
     */
    public function getDeployment(): ?string
    {
        if (count($this->deployment) == 0) {
            return null;
        }
        return $this->deployment['value'];
    }

    /**
     * Sets Deployment.
     * Optional deployment identifier
     *
     * @maps deployment
     */
    public function setDeployment(?string $deployment): void
    {
        $this->deployment['value'] = $deployment;
    }

    /**
     * Unsets Deployment.
     * Optional deployment identifier
     */
    public function unsetDeployment(): void
    {
        $this->deployment = [];
    }

    /**
     * Converts the UsageBreakdownV1ResponseResultsItemsGrouping object to a human-readable string
     * representation.
     *
     * @return string The string representation of the UsageBreakdownV1ResponseResultsItemsGrouping object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UsageBreakdownV1ResponseResultsItemsGrouping',
            [
                'start' => $this->start,
                'end' => $this->end,
                'accessor' => $this->getAccessor(),
                'endpoint' => $this->getEndpoint(),
                'featureSet' => $this->getFeatureSet(),
                'models' => $this->models,
                'method' => $this->getMethod(),
                'tags' => $this->getTags(),
                'deployment' => $this->getDeployment(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'start',
        'end',
        'accessor',
        'endpoint',
        'feature_set',
        'models',
        'method',
        'tags',
        'deployment'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->start)) {
            $json['start']       = DateTimeHelper::toSimpleDate($this->start);
        }
        if (isset($this->end)) {
            $json['end']         = DateTimeHelper::toSimpleDate($this->end);
        }
        if (!empty($this->accessor)) {
            $json['accessor']    = $this->accessor['value'];
        }
        if (!empty($this->endpoint)) {
            $json['endpoint']    = $this->endpoint['value'];
        }
        if (!empty($this->featureSet)) {
            $json['feature_set'] = $this->featureSet['value'];
        }
        if (isset($this->models)) {
            $json['models']      = $this->models;
        }
        if (!empty($this->method)) {
            $json['method']      = $this->method['value'];
        }
        if (!empty($this->tags)) {
            $json['tags']        = $this->tags['value'];
        }
        if (!empty($this->deployment)) {
            $json['deployment']  = $this->deployment['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
