<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use RestApiLib\ApiHelper;
use stdClass;

class UsageFieldsV1Response implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $tags;

    /**
     * @var UsageFieldsV1ResponseModelsItems[]|null
     */
    private $models;

    /**
     * @var string[]|null
     */
    private $processingMethods;

    /**
     * @var string[]|null
     */
    private $features;

    /**
     * Returns Tags.
     * List of tags associated with the project
     *
     * @return string[]|null
     */
    public function getTags(): ?array
    {
        return $this->tags;
    }

    /**
     * Sets Tags.
     * List of tags associated with the project
     *
     * @maps tags
     *
     * @param string[]|null $tags
     */
    public function setTags(?array $tags): void
    {
        $this->tags = $tags;
    }

    /**
     * Returns Models.
     * List of models available for the project.
     *
     * @return UsageFieldsV1ResponseModelsItems[]|null
     */
    public function getModels(): ?array
    {
        return $this->models;
    }

    /**
     * Sets Models.
     * List of models available for the project.
     *
     * @maps models
     *
     * @param UsageFieldsV1ResponseModelsItems[]|null $models
     */
    public function setModels(?array $models): void
    {
        $this->models = $models;
    }

    /**
     * Returns Processing Methods.
     * Processing methods supported by the API
     *
     * @return string[]|null
     */
    public function getProcessingMethods(): ?array
    {
        return $this->processingMethods;
    }

    /**
     * Sets Processing Methods.
     * Processing methods supported by the API
     *
     * @maps processing_methods
     *
     * @param string[]|null $processingMethods
     */
    public function setProcessingMethods(?array $processingMethods): void
    {
        $this->processingMethods = $processingMethods;
    }

    /**
     * Returns Features.
     * API features available to the project
     *
     * @return string[]|null
     */
    public function getFeatures(): ?array
    {
        return $this->features;
    }

    /**
     * Sets Features.
     * API features available to the project
     *
     * @maps features
     *
     * @param string[]|null $features
     */
    public function setFeatures(?array $features): void
    {
        $this->features = $features;
    }

    /**
     * Converts the UsageFieldsV1Response object to a human-readable string representation.
     *
     * @return string The string representation of the UsageFieldsV1Response object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UsageFieldsV1Response',
            [
                'tags' => $this->tags,
                'models' => $this->models,
                'processingMethods' => $this->processingMethods,
                'features' => $this->features,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['tags', 'models', 'processing_methods', 'features'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->tags)) {
            $json['tags']               = $this->tags;
        }
        if (isset($this->models)) {
            $json['models']             = $this->models;
        }
        if (isset($this->processingMethods)) {
            $json['processing_methods'] = $this->processingMethods;
        }
        if (isset($this->features)) {
            $json['features']           = $this->features;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
