<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Our public models available to all accounts
 */
class V1ListenPostParametersModel0
{
    public const NOVA3 = 'nova-3';

    public const NOVA3GENERAL = 'nova-3-general';

    public const NOVA3MEDICAL = 'nova-3-medical';

    public const NOVA2 = 'nova-2';

    public const NOVA2GENERAL = 'nova-2-general';

    public const NOVA2MEETING = 'nova-2-meeting';

    public const NOVA2FINANCE = 'nova-2-finance';

    public const NOVA2CONVERSATIONALAI = 'nova-2-conversationalai';

    public const NOVA2VOICEMAIL = 'nova-2-voicemail';

    public const NOVA2VIDEO = 'nova-2-video';

    public const NOVA2MEDICAL = 'nova-2-medical';

    public const NOVA2DRIVETHRU = 'nova-2-drivethru';

    public const NOVA2AUTOMOTIVE = 'nova-2-automotive';

    public const NOVA = 'nova';

    public const NOVAGENERAL = 'nova-general';

    public const NOVAPHONECALL = 'nova-phonecall';

    public const NOVAMEDICAL = 'nova-medical';

    public const ENHANCED = 'enhanced';

    public const ENHANCEDGENERAL = 'enhanced-general';

    public const ENHANCEDMEETING = 'enhanced-meeting';

    public const ENHANCEDPHONECALL = 'enhanced-phonecall';

    public const ENHANCEDFINANCE = 'enhanced-finance';

    public const BASE = 'base';

    public const MEETING = 'meeting';

    public const PHONECALL = 'phonecall';

    public const FINANCE = 'finance';

    public const CONVERSATIONALAI = 'conversationalai';

    public const VOICEMAIL = 'voicemail';

    public const VIDEO = 'video';

    private const _ALL_VALUES = [
        self::NOVA3,
        self::NOVA3GENERAL,
        self::NOVA3MEDICAL,
        self::NOVA2,
        self::NOVA2GENERAL,
        self::NOVA2MEETING,
        self::NOVA2FINANCE,
        self::NOVA2CONVERSATIONALAI,
        self::NOVA2VOICEMAIL,
        self::NOVA2VIDEO,
        self::NOVA2MEDICAL,
        self::NOVA2DRIVETHRU,
        self::NOVA2AUTOMOTIVE,
        self::NOVA,
        self::NOVAGENERAL,
        self::NOVAPHONECALL,
        self::NOVAMEDICAL,
        self::ENHANCED,
        self::ENHANCEDGENERAL,
        self::ENHANCEDMEETING,
        self::ENHANCEDPHONECALL,
        self::ENHANCEDFINANCE,
        self::BASE,
        self::MEETING,
        self::PHONECALL,
        self::FINANCE,
        self::CONVERSATIONALAI,
        self::VOICEMAIL,
        self::VIDEO
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for V1ListenPostParametersModel0.");
    }
}
