<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems
{
    public const ENUM_SELFHOSTEDPRODUCTS = 'self-hosted:products';

    public const ENUM_SELFHOSTEDPRODUCTAPI = 'self-hosted:product:api';

    public const ENUM_SELFHOSTEDPRODUCTENGINE = 'self-hosted:product:engine';

    public const ENUM_SELFHOSTEDPRODUCTLICENSEPROXY = 'self-hosted:product:license-proxy';

    public const ENUM_SELFHOSTEDPRODUCTDGTOOLS = 'self-hosted:product:dgtools';

    public const ENUM_SELFHOSTEDPRODUCTBILLING = 'self-hosted:product:billing';

    public const ENUM_SELFHOSTEDPRODUCTHOTPEPPER = 'self-hosted:product:hotpepper';

    public const ENUM_SELFHOSTEDPRODUCTMETRICSSERVER = 'self-hosted:product:metrics-server';

    private const _ALL_VALUES = [
        self::ENUM_SELFHOSTEDPRODUCTS,
        self::ENUM_SELFHOSTEDPRODUCTAPI,
        self::ENUM_SELFHOSTEDPRODUCTENGINE,
        self::ENUM_SELFHOSTEDPRODUCTLICENSEPROXY,
        self::ENUM_SELFHOSTEDPRODUCTDGTOOLS,
        self::ENUM_SELFHOSTEDPRODUCTBILLING,
        self::ENUM_SELFHOSTEDPRODUCTHOTPEPPER,
        self::ENUM_SELFHOSTEDPRODUCTMETRICSSERVER
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for V1ProjectsProjectIdSelfHostedDistributionCredentialsPostParametersScopesSchemaItems.");
    }
}
