<?php

declare(strict_types=1);

/*
 * RestApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace RestApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class V1SpeakPostParametersModel
{
    public const AURAANGUSEN = 'aura-angus-en';

    public const AURAARCASEN = 'aura-arcas-en';

    public const AURAASTERIAEN = 'aura-asteria-en';

    public const AURAATHENAEN = 'aura-athena-en';

    public const AURAHELIOSEN = 'aura-helios-en';

    public const AURAHERAEN = 'aura-hera-en';

    public const AURALUNAEN = 'aura-luna-en';

    public const AURAORIONEN = 'aura-orion-en';

    public const AURAORPHEUSEN = 'aura-orpheus-en';

    public const AURAPERSEUSEN = 'aura-perseus-en';

    public const AURASTELLAEN = 'aura-stella-en';

    public const AURAZEUSEN = 'aura-zeus-en';

    public const AURA2AMALTHEAEN = 'aura-2-amalthea-en';

    public const AURA2ANDROMEDAEN = 'aura-2-andromeda-en';

    public const AURA2APOLLOEN = 'aura-2-apollo-en';

    public const AURA2ARCASEN = 'aura-2-arcas-en';

    public const AURA2ARIESEN = 'aura-2-aries-en';

    public const AURA2ASTERIAEN = 'aura-2-asteria-en';

    public const AURA2ATHENAEN = 'aura-2-athena-en';

    public const AURA2ATLASEN = 'aura-2-atlas-en';

    public const AURA2AURORAEN = 'aura-2-aurora-en';

    public const AURA2CALLISTAEN = 'aura-2-callista-en';

    public const AURA2CORAEN = 'aura-2-cora-en';

    public const AURA2CORDELIAEN = 'aura-2-cordelia-en';

    public const AURA2DELIAEN = 'aura-2-delia-en';

    public const AURA2DRACOEN = 'aura-2-draco-en';

    public const AURA2ELECTRAEN = 'aura-2-electra-en';

    public const AURA2HARMONIAEN = 'aura-2-harmonia-en';

    public const AURA2HELENAEN = 'aura-2-helena-en';

    public const AURA2HERAEN = 'aura-2-hera-en';

    public const AURA2HERMESEN = 'aura-2-hermes-en';

    public const AURA2HYPERIONEN = 'aura-2-hyperion-en';

    public const AURA2IRISEN = 'aura-2-iris-en';

    public const AURA2JANUSEN = 'aura-2-janus-en';

    public const AURA2JUNOEN = 'aura-2-juno-en';

    public const AURA2JUPITEREN = 'aura-2-jupiter-en';

    public const AURA2LUNAEN = 'aura-2-luna-en';

    public const AURA2MARSEN = 'aura-2-mars-en';

    public const AURA2MINERVAEN = 'aura-2-minerva-en';

    public const AURA2NEPTUNEEN = 'aura-2-neptune-en';

    public const AURA2ODYSSEUSEN = 'aura-2-odysseus-en';

    public const AURA2OPHELIAEN = 'aura-2-ophelia-en';

    public const AURA2ORIONEN = 'aura-2-orion-en';

    public const AURA2ORPHEUSEN = 'aura-2-orpheus-en';

    public const AURA2PANDORAEN = 'aura-2-pandora-en';

    public const AURA2PHOEBEEN = 'aura-2-phoebe-en';

    public const AURA2PLUTOEN = 'aura-2-pluto-en';

    public const AURA2SATURNEN = 'aura-2-saturn-en';

    public const AURA2SELENEEN = 'aura-2-selene-en';

    public const AURA2THALIAEN = 'aura-2-thalia-en';

    public const AURA2THEIAEN = 'aura-2-theia-en';

    public const AURA2VESTAEN = 'aura-2-vesta-en';

    public const AURA2ZEUSEN = 'aura-2-zeus-en';

    public const AURA2AGUSTINAES = 'aura-2-agustina-es';

    public const AURA2ALVAROES = 'aura-2-alvaro-es';

    public const AURA2ANTONIAES = 'aura-2-antonia-es';

    public const AURA2AQUILAES = 'aura-2-aquila-es';

    public const AURA2CARINAES = 'aura-2-carina-es';

    public const AURA2CELESTEES = 'aura-2-celeste-es';

    public const AURA2DIANAES = 'aura-2-diana-es';

    public const AURA2ESTRELLAES = 'aura-2-estrella-es';

    public const AURA2GLORIAES = 'aura-2-gloria-es';

    public const AURA2JAVIERES = 'aura-2-javier-es';

    public const AURA2LUCIANOES = 'aura-2-luciano-es';

    public const AURA2NESTORES = 'aura-2-nestor-es';

    public const AURA2OLIVIAES = 'aura-2-olivia-es';

    public const AURA2SELENAES = 'aura-2-selena-es';

    public const AURA2SILVIAES = 'aura-2-silvia-es';

    public const AURA2SIRIOES = 'aura-2-sirio-es';

    public const AURA2VALERIOES = 'aura-2-valerio-es';

    public const AURA2AURELIADE = 'aura-2-aurelia-de';

    public const AURA2ELARADE = 'aura-2-elara-de';

    public const AURA2FABIANDE = 'aura-2-fabian-de';

    public const AURA2JULIUSDE = 'aura-2-julius-de';

    public const AURA2KARADE = 'aura-2-kara-de';

    public const AURA2LARADE = 'aura-2-lara-de';

    public const AURA2VIKTORIADE = 'aura-2-viktoria-de';

    public const AURA2BEATRIXNL = 'aura-2-beatrix-nl';

    public const AURA2CORNELIANL = 'aura-2-cornelia-nl';

    public const AURA2DAPHNENL = 'aura-2-daphne-nl';

    public const AURA2HESTIANL = 'aura-2-hestia-nl';

    public const AURA2LARSNL = 'aura-2-lars-nl';

    public const AURA2LEDANL = 'aura-2-leda-nl';

    public const AURA2RHEANL = 'aura-2-rhea-nl';

    public const AURA2ROMANNL = 'aura-2-roman-nl';

    public const AURA2SANDERNL = 'aura-2-sander-nl';

    public const AURA2AGATHEFR = 'aura-2-agathe-fr';

    public const AURA2HECTORFR = 'aura-2-hector-fr';

    public const AURA2CESAREIT = 'aura-2-cesare-it';

    public const AURA2CINZIAIT = 'aura-2-cinzia-it';

    public const AURA2DEMETRAIT = 'aura-2-demetra-it';

    public const AURA2DIONISIOIT = 'aura-2-dionisio-it';

    public const AURA2ELIOIT = 'aura-2-elio-it';

    public const AURA2FLAVIOIT = 'aura-2-flavio-it';

    public const AURA2LIVIAIT = 'aura-2-livia-it';

    public const AURA2MAIAIT = 'aura-2-maia-it';

    public const AURA2MELIAIT = 'aura-2-melia-it';

    public const AURA2PERSEOIT = 'aura-2-perseo-it';

    public const AURA2AMAJA = 'aura-2-ama-ja';

    public const AURA2EBISUJA = 'aura-2-ebisu-ja';

    public const AURA2FUJINJA = 'aura-2-fujin-ja';

    public const AURA2IZANAMIJA = 'aura-2-izanami-ja';

    public const AURA2UZUMEJA = 'aura-2-uzume-ja';

    private const _ALL_VALUES = [
        self::AURAANGUSEN,
        self::AURAARCASEN,
        self::AURAASTERIAEN,
        self::AURAATHENAEN,
        self::AURAHELIOSEN,
        self::AURAHERAEN,
        self::AURALUNAEN,
        self::AURAORIONEN,
        self::AURAORPHEUSEN,
        self::AURAPERSEUSEN,
        self::AURASTELLAEN,
        self::AURAZEUSEN,
        self::AURA2AMALTHEAEN,
        self::AURA2ANDROMEDAEN,
        self::AURA2APOLLOEN,
        self::AURA2ARCASEN,
        self::AURA2ARIESEN,
        self::AURA2ASTERIAEN,
        self::AURA2ATHENAEN,
        self::AURA2ATLASEN,
        self::AURA2AURORAEN,
        self::AURA2CALLISTAEN,
        self::AURA2CORAEN,
        self::AURA2CORDELIAEN,
        self::AURA2DELIAEN,
        self::AURA2DRACOEN,
        self::AURA2ELECTRAEN,
        self::AURA2HARMONIAEN,
        self::AURA2HELENAEN,
        self::AURA2HERAEN,
        self::AURA2HERMESEN,
        self::AURA2HYPERIONEN,
        self::AURA2IRISEN,
        self::AURA2JANUSEN,
        self::AURA2JUNOEN,
        self::AURA2JUPITEREN,
        self::AURA2LUNAEN,
        self::AURA2MARSEN,
        self::AURA2MINERVAEN,
        self::AURA2NEPTUNEEN,
        self::AURA2ODYSSEUSEN,
        self::AURA2OPHELIAEN,
        self::AURA2ORIONEN,
        self::AURA2ORPHEUSEN,
        self::AURA2PANDORAEN,
        self::AURA2PHOEBEEN,
        self::AURA2PLUTOEN,
        self::AURA2SATURNEN,
        self::AURA2SELENEEN,
        self::AURA2THALIAEN,
        self::AURA2THEIAEN,
        self::AURA2VESTAEN,
        self::AURA2ZEUSEN,
        self::AURA2AGUSTINAES,
        self::AURA2ALVAROES,
        self::AURA2ANTONIAES,
        self::AURA2AQUILAES,
        self::AURA2CARINAES,
        self::AURA2CELESTEES,
        self::AURA2DIANAES,
        self::AURA2ESTRELLAES,
        self::AURA2GLORIAES,
        self::AURA2JAVIERES,
        self::AURA2LUCIANOES,
        self::AURA2NESTORES,
        self::AURA2OLIVIAES,
        self::AURA2SELENAES,
        self::AURA2SILVIAES,
        self::AURA2SIRIOES,
        self::AURA2VALERIOES,
        self::AURA2AURELIADE,
        self::AURA2ELARADE,
        self::AURA2FABIANDE,
        self::AURA2JULIUSDE,
        self::AURA2KARADE,
        self::AURA2LARADE,
        self::AURA2VIKTORIADE,
        self::AURA2BEATRIXNL,
        self::AURA2CORNELIANL,
        self::AURA2DAPHNENL,
        self::AURA2HESTIANL,
        self::AURA2LARSNL,
        self::AURA2LEDANL,
        self::AURA2RHEANL,
        self::AURA2ROMANNL,
        self::AURA2SANDERNL,
        self::AURA2AGATHEFR,
        self::AURA2HECTORFR,
        self::AURA2CESAREIT,
        self::AURA2CINZIAIT,
        self::AURA2DEMETRAIT,
        self::AURA2DIONISIOIT,
        self::AURA2ELIOIT,
        self::AURA2FLAVIOIT,
        self::AURA2LIVIAIT,
        self::AURA2MAIAIT,
        self::AURA2MELIAIT,
        self::AURA2PERSEOIT,
        self::AURA2AMAJA,
        self::AURA2EBISUJA,
        self::AURA2FUJINJA,
        self::AURA2IZANAMIJA,
        self::AURA2UZUMEJA
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for V1SpeakPostParametersModel.");
    }
}
