<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Encoding - flac. Supported sample rates - 8000, 16000, 22050, 32000, 48000 Hz.
 */
class V2SpeakPostParametersSampleRate3
{
    public const ENUM_8000 = '8000';

    public const ENUM_16000 = '16000';

    public const ENUM_22050 = '22050';

    public const ENUM_32000 = '32000';

    public const ENUM_48000 = '48000';

    private const _ALL_VALUES =
        [self::ENUM_8000, self::ENUM_16000, self::ENUM_22050, self::ENUM_32000, self::ENUM_48000];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for V2SpeakPostParametersSampleRate3.");
    }
}
