<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Encoding - linear16. Uncompressed, high-quality audio format often used for telephony or audio
 * processing.
 */
class V2SpeakPostParametersEncoding0
{
    public const LINEAR16 = 'linear16';

    private const _ALL_VALUES = [self::LINEAR16];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for V2SpeakPostParametersEncoding0.");
    }
}
