<?php

declare(strict_types=1);

/*
 * Deepgram
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DeepgramLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Production
     */
    public const PRODUCTION = 'production';

    /**
     * Base
     */
    public const ENVIRONMENT2 = 'environment2';
}
